  {
    title: "The Goldfinch",
    year: "1654",
    originalSize: "33.4 x 22.8 cm",
    artist: "Carel Fabritius",
    artistLife: "1622-1654",
    sku: "AM-F-001",
    basePrice: 1671,
    currency: "AED",
    image: "/image/f/the-goldfinch.jpg",
    options: [{ id: 'opt1', width: 33.4, height: 22.8, price: 1671, label: 'Original Size' }],
  },

  {
    title: "The Beheading Of Saint John The Baptist",
    year: "1640",
    originalSize: "149 x 121 cm",
    artist: "Carel Fabritius",
    artistLife: "1622-1654",
    sku: "AM-F-002",
    basePrice: 16841,
    currency: "AED",
    image: "/image/f/the-beheading-of-saint-john-the-baptist.jpg",
    options: [{ id: 'opt1', width: 149, height: 121, price: 16841, label: 'Original Size' }],
  },

  {
    title: "The Sentry",
    year: "1654",
    originalSize: "67 x 58 cm",
    artist: "Carel Fabritius",
    artistLife: "1622-1654",
    sku: "AM-F-003",
    basePrice: 1654,
    currency: "AED",
    image: "/image/f/the-sentry.jpg",
    options: [{ id: 'opt1', width: 67, height: 58, price: 1654, label: 'Original Size' }],
  },

  {
    title: "Roses And Lilies",
    year: "1888",
    originalSize: "59.7 x 45.7 cm",
    artist: "Henri Fantin Latour",
    artistLife: "1836-1904",
    sku: "AM-F-004",
    basePrice: 4122,
    currency: "AED",
    image: "/image/f/rose-and-lilies.jpg",
    options: [{ id: 'opt1', width: 59.7, height: 45.7, price: 4122, label: 'Original Size' }],
  },

  {
    title: "Still Life With Roses And Fruit",
    year: "1868",
    originalSize: "34.6 x 41.6 cm",
    artist: "Henri Fantin Latour",
    artistLife: "1836-1904",
    sku: "AM-F-005",
    basePrice: 3276,
    currency: "AED",
    image: "/image/f/still-life-with-roses-and-fruit.jpg",
    options: [{ id: 'opt1', width: 34.6, height: 41.6, price: 3276, label: 'Original Size' }],
  },

  {
    title: "The Reader",
    year: "1861",
    originalSize: "100 x 83 cm",
    artist: "Henri Fantin Latour",
    artistLife: "1836-1904",
    sku: "AM-F-006",
    basePrice: 4964,
    currency: "AED",
    image: "/image/f/the-reader.jpg",
    options: [{ id: 'opt1', width: 100, height: 83, price: 4964, label: 'Original Size' }],
  },

  {
    title: "The Dressed Table",
    year: "1866",
    originalSize: "60 x 74 cm",
    artist: "Henri Fantin Latour",
    artistLife: "1836-1904",
    sku: "AM-F-007",
    basePrice: 6065,
    currency: "AED",
    image: "/image/f/the-dressed-table.jpg",
    options: [{ id: 'opt1', width: 60, height: 74, price: 6065, label: 'Original Size' }],
  },

  {
    title: "Peaches And Grapes",
    year: "1894",
    originalSize: "27.3 x 36.4 cm",
    artist: "Henri Fantin Latour",
    artistLife: "1836-1904",
    sku: "AM-F-008",
    basePrice: 2875,
    currency: "AED",
    image: "/image/f/peaches-and-grapes.jpg",
    options: [{ id: 'opt1', width: 27.3, height: 36.4, price: 2875, label: 'Original Size' }],
  },

  {
    title: "Nanna",
    year: "1861",
    originalSize: "91 x 66 cm",
    artist: "Anselm Feuerbach",
    artistLife: "1829-1880",
    sku: "AM-F-009",
    basePrice: 5651,
    currency: "AED",
    image: "/image/f/nanna.jpg",
    options: [{ id: 'opt1', width: 91, height: 66, price: 5651, label: 'Original Size' }],
  },

  {
    title: "Nanna",
    year: "1861",
    originalSize: "74.5 x 62 cm",
    artist: "Anselm Feuerbach",
    artistLife: "1829-1880",
    sku: "AM-F-010",
    basePrice: 5240,
    currency: "AED",
    image: "/image/f/nanna-1.jpg",
    options: [{ id: 'opt1', width: 74.5, height: 62, price: 5240, label: 'Original Size' }],
  },

  {
    title: "Self Portrait",
    year: "1854",
    originalSize: "92 x 73 cm",
    artist: "Anselm Feuerbach",
    artistLife: "1829-1880",
    sku: "AM-F-011",
    basePrice: 5612,
    currency: "AED",
    image: "/image/f/self-portrait.jpg",
    options: [{ id: 'opt1', width: 92, height: 73, price: 5612, label: 'Original Size' }],
  },

  {
    title: "Mandolin Player",
    year: "1868",
    originalSize: "137 x 98.5 cm",
    artist: "Anselm Feuerbach",
    artistLife: "1829-1880",
    sku: "AM-F-012",
    basePrice: 8568,
    currency: "AED",
    image: "/image/f/mandolin-player.jpg",
    options: [{ id: 'opt1', width: 137, height: 98.5, price: 8568, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Princess Zinaida Yusupova With Two Sons At Arkhangelskoe",
    year: "1894",
    originalSize: "75 x 59 cm",
    artist: "Francois Flameng",
    artistLife: "1856-1923",
    sku: "AM-F-013",
    basePrice: 6988,
    currency: "AED",
    image: "/image/f/portrait-of-princess-zinaida-yusupova-with-two-sons-at-arkhangelskoe.jpg",
    options: [{ id: 'opt1', width: 75, height: 59, price: 6988, label: 'Original Size' }],
  },

  {
    title: "Family Portrait Of A Boy And His Two Sisters",
    year: "1900",
    originalSize: "65 x 54 cm",
    artist: "Francois Flameng",
    artistLife: "1856-1923",
    sku: "AM-F-014",
    basePrice: 3854,
    currency: "AED",
    image: "/image/f/family-portrait-of-a-boy-and-his-two-sisters.jpg",
    options: [{ id: 'opt1', width: 65, height: 54, price: 3854, label: 'Original Size' }],
  },

  {
    title: "Nude Youth Sitting By The Sea",
    year: "1836",
    originalSize: "98 x 124 cm",
    artist: "Hippolyte Flandrin",
    artistLife: "1809-1864",
    sku: "AM-F-015",
    basePrice: 8633,
    currency: "AED",
    image: "/image/f/nude-youth-sitting-by-the-sea.jpg",
    options: [{ id: 'opt1', width: 98, height: 124, price: 8633, label: 'Original Size' }],
  },

  {
    title: "Madam Hippolyte Flandrin",
    year: "1846",
    originalSize: "83 x 66 cm",
    artist: "Hippolyte Flandrin",
    artistLife: "1809-1864",
    sku: "AM-F-016",
    basePrice: 7800,
    currency: "AED",
    image: "/image/f/madam-hippolyte-flandrin.jpg",
    options: [{ id: 'opt1', width: 83, height: 66, price: 7800, label: 'Original Size' }],
  },

  {
    title: "Maria-Anne De Bourbon Duchesse De Vendome",
    year: "1839",
    originalSize: "77 x 59 cm",
    artist: "Hippolyte Flandrin",
    artistLife: "1809-1864",
    sku: "AM-F-017",
    basePrice: 8113,
    currency: "AED",
    image: "/image/f/maria-anne-de-bourbon-duchesse-de-vendome.jpg",
    options: [{ id: 'opt1', width: 77, height: 59, price: 8113, label: 'Original Size' }],
  },

  {
    title: "Still Life With Bread And Confectinary",
    year: "Unknown",
    originalSize: "21.9 x 17.1 cm",
    artist: "Georg Flegel",
    artistLife: "1566-1638",
    sku: "AM-F-018",
    basePrice: 6026,
    currency: "AED",
    image: "/image/f/still-life-with-bread-and-confectinary.jpg",
    options: [{ id: 'opt1', width: 21.9, height: 17.1, price: 6026, label: 'Original Size' }],
  },

  {
    title: "Still Life Pretzels, Nuts and Almonds",
    year: "1637",
    originalSize: "19.3 x 14.6 cm",
    artist: "Georg Flegel",
    artistLife: "1566-1638",
    sku: "AM-F-019",
    basePrice: 9348,
    currency: "AED",
    image: "/image/f/still-life-pretzels-nuts-and-almonds.jpg",
    options: [{ id: 'opt1', width: 19.3, height: 14.6, price: 9348, label: 'Original Size' }],
  },

  {
    title: "Snack With Fried Eggs",
    year: "1630",
    originalSize: "23.6 x 20.2 cm",
    artist: "Georg Flegel",
    artistLife: "1566-1638",
    sku: "AM-F-020",
    basePrice: 9845,
    currency: "AED",
    image: "/image/f/snack-with-fried-eggs.jpg",
    options: [{ id: 'opt1', width: 23.6, height: 20.2, price: 9845, label: 'Original Size' }],
  },

  {
    title: "Meal With Pike Head",
    year: "Unknown",
    originalSize: "31.4 x 40 cm",
    artist: "Georg Flegel",
    artistLife: "1566-1638",
    sku: "AM-F-021",
    basePrice: 17932,
    currency: "AED",
    image: "/image/f/meal-with-pike-head.jpg",
    options: [{ id: 'opt1', width: 31.4, height: 40, price: 17932, label: 'Original Size' }],
  },

  {
    title: "Swans In The Reeds",
    year: "1820",
    originalSize: "34 x 44 cm",
    artist: "Caspar David Friedrich",
    artistLife: "1774-1840",
    sku: "AM-F-022",
    basePrice: 3698,
    currency: "AED",
    image: "/image/f/swans-in-the-reeds.jpg",
    options: [{ id: 'opt1', width: 34, height: 44, price: 3698, label: 'Original Size' }],
  },

  {
    title: "Caroline On The Stairs",
    year: "1825",
    originalSize: "73.6 x 52 cm",
    artist: "Caspar David Friedrich",
    artistLife: "1774-1840",
    sku: "AM-F-023",
    basePrice: 3844,
    currency: "AED",
    image: "/image/f/caroline-on-the-stairs.jpg",
    options: [{ id: 'opt1', width: 73.6, height: 52, price: 3844, label: 'Original Size' }],
  },

  {
    title: "Ship In The Polar Sea",
    year: "1798",
    originalSize: "29.6 x 21.9 cm",
    artist: "Caspar David Friedrich",
    artistLife: "1774-1840",
    sku: "AM-F-024",
    basePrice: 3011,
    currency: "AED",
    image: "/image/f/ship-in-the-polar-sea.jpg",
    options: [{ id: 'opt1', width: 29.6, height: 21.9, price: 3011, label: 'Original Size' }],
  },

