  {
    title: "The Pond October",
    year: "1921",
    originalSize: "74.3 x 95 cm",
    artist: "Clarence Ganon",
    artistLife: "1881-1921",
    sku: "AM-G-001",
    basePrice: 3050,
    currency: "AED",
    image: "/image/g/the pond october.jpg",
    options: [{ id: 'opt1', width: 74.3, height: 95, price: 3050, label: 'Original Size' }],
  },

  {
    title: "After The Storm",
    year: "1922",
    originalSize: "16 x 23.5 cm",
    artist: "Clarence Ganon",
    artistLife: "1881-1921",
    sku: "AM-G-002",
    basePrice: 1412,
    currency: "AED",
    image: "/image/g/after the storm.jpg",
    options: [{ id: 'opt1', width: 16, height: 23.5, price: 1412, label: 'Original Size' }],
  },

  {
    title: "Village In The Laurentian Mountains",
    year: "1925",
    originalSize: "89.2 x 130.7 cm",
    artist: "Clarence Ganon",
    artistLife: "1881-1921",
    sku: "AM-G-003",
    basePrice: 6597,
    currency: "AED",
    image: "/image/g/village in the laurentian mountains.jpg",
    options: [{ id: 'opt1', width: 89.2, height: 130.7, price: 6597, label: 'Original Size' }],
  },

  {
    title: "Street Scene Quebec At Night",
    year: "1917",
    originalSize: "56.4 x 74.4 cm",
    artist: "Clarence Ganon",
    artistLife: "1881-1921",
    sku: "AM-G-004",
    basePrice: 1987,
    currency: "AED",
    image: "/image/g/street scene quebec at night.jpg",
    options: [{ id: 'opt1', width: 56.4, height: 74.4, price: 1987, label: 'Original Size' }],
  },

  {
    title: "The Woman In Blue (Portrait Of Duchess Of Beaufort)",
    year: "1775",
    originalSize: "76 x 64 cm",
    artist: "Thomas Gainsborough",
    artistLife: "1727-1788",
    sku: "AM-G-005",
    basePrice: 5556,
    currency: "AED",
    image: "/image/g/the woman in blue (portrait of duchess of beaufort).jpg",
    options: [{ id: 'opt1', width: 76, height: 64, price: 5556, label: 'Original Size' }],
  },

  {
    title: "The Mall In St James Park",
    year: "1783",
    originalSize: "120.6 x 147 cm",
    artist: "Thomas Gainsborough",
    artistLife: "1727-1788",
    sku: "AM-G-006",
    basePrice: 16413,
    currency: "AED",
    image: "/image/g/the mall in st james park.jpg",
    options: [{ id: 'opt1', width: 120.6, height: 147, price: 16413, label: 'Original Size' }],
  },

  {
    title: "Conversation In A Park",
    year: "1746",
    originalSize: "73 x 68 cm",
    artist: "Thomas Gainsborough",
    artistLife: "1727-1788",
    sku: "AM-G-007",
    basePrice: 5500,
    currency: "AED",
    image: "/image/g/conversation in a park.jpg",
    options: [{ id: 'opt1', width: 73, height: 68, price: 5500, label: 'Original Size' }],
  },

  {
    title: "A Pug",
    year: "1780",
    originalSize: "48.5 x 59 cm",
    artist: "Thomas Gainsborough",
    artistLife: "1727-1788",
    sku: "AM-G-008",
    basePrice: 4225,
    currency: "AED",
    image: "/image/g/a pug.jpg",
    options: [{ id: 'opt1', width: 48.5, height: 59, price: 4225, label: 'Original Size' }],
  },

  {
    title: "Idyll In Tahiti",
    year: "1901",
    originalSize: "74.5 x 94.5 cm",
    artist: "Paul Gauguin",
    artistLife: "1848-1903",
    sku: "AM-G-009",
    basePrice: 3137,
    currency: "AED",
    image: "/image/g/idyll in tahiti.jpg",
    options: [{ id: 'opt1', width: 74.5, height: 94.5, price: 3137, label: 'Original Size' }],
  },

  {
    title: "Still Life Sunflowers On An Armchair",
    year: "1901",
    originalSize: "68 x 75.5 cm",
    artist: "Paul Gauguin",
    artistLife: "1848-1903",
    sku: "AM-G-010",
    basePrice: 2991,
    currency: "AED",
    image: "/image/g/still life sunflowers on an armchair.jpg",
    options: [{ id: 'opt1', width: 68, height: 75.5, price: 2991, label: 'Original Size' }],
  },

  {
    title: "Three Tahitians",
    year: "1894",
    originalSize: "73 x 94 cm",
    artist: "Paul Gauguin",
    artistLife: "1848-1903",
    sku: "AM-G-011",
    basePrice: 2625,
    currency: "AED",
    image: "/image/g/three tahitians.jpg",
    options: [{ id: 'opt1', width: 73, height: 94, price: 2625, label: 'Original Size' }],
  },

  {
    title: "Two Tahitian Woman",
    year: "1899",
    originalSize: "94 x 72.4 cm",
    artist: "Paul Gauguin",
    artistLife: "1848-1903",
    sku: "AM-G-012",
    basePrice: 2798,
    currency: "AED",
    image: "/image/g/two tahitian woman.jpg",
    options: [{ id: 'opt1', width: 94, height: 72.4, price: 2798, label: 'Original Size' }],
  },

  {
    title: "The Grey Cardinal",
    year: "1873",
    originalSize: "68.6 x 101 cm",
    artist: "Jean Leon Gerome",
    artistLife: "1824-1904",
    sku: "AM-G-013",
    basePrice: 12163,
    currency: "AED",
    image: "/image/g/the grey cardinal.jpg",
    options: [{ id: 'opt1', width: 68.6, height: 101, price: 12163, label: 'Original Size' }],
  },

  {
    title: "Pelt Merchant Of Cairo",
    year: "1880",
    originalSize: "61.5 x 50.2 cm",
    artist: "Jean Leon Gerome",
    artistLife: "1824-1904",
    sku: "AM-G-014",
    basePrice: 5912,
    currency: "AED",
    image: "/image/g/pelt merchant of cairo.jpg",
    options: [{ id: 'opt1', width: 61.5, height: 50.2, price: 5912, label: 'Original Size' }],
  },

  {
    title: "Pollice Verso (Thumbs Down)",
    year: "1872",
    originalSize: "100 x 149.2 cm",
    artist: "Jean Leon Gerome",
    artistLife: "1824-1904",
    sku: "AM-G-015",
    basePrice: 20762,
    currency: "AED",
    image: "/image/g/pollice verso (thumbs down).jpg",
    options: [{ id: 'opt1', width: 100, height: 149.2, price: 20762, label: 'Original Size' }],
  },

  {
    title: "Prayer In Cairo On The Rooftops",
    year: "1865",
    originalSize: "49.9 x 81.2 cm",
    artist: "Jean Leon Gerome",
    artistLife: "1824-1904",
    sku: "AM-G-016",
    basePrice: 7643,
    currency: "AED",
    image: "/image/g/prayer in cairo on the rooftops.jpg",
    options: [{ id: 'opt1', width: 49.9, height: 81.2, price: 7643, label: 'Original Size' }],
  },

  {
    title: "The Entombment Of Atala (The Burial Of Atala)",
    year: "1808",
    originalSize: "207 x 267 cm",
    artist: "Anne-Louis Girodet De Roussy-Trioson",
    artistLife: "1767-1824",
    sku: "AM-G-017",
    basePrice: 39578,
    currency: "AED",
    image: "/image/g/the entombmeent of atala (the burial of atala).jpg",
    options: [{ id: 'opt1', width: 207, height: 267, price: 39578, label: 'Original Size' }],
  },

  {
    title: "Napoleon In Coronation Robes",
    year: "1812",
    originalSize: "256 x 183.3 cm",
    artist: "Anne-Louis Girodet De Roussy-Trioson",
    artistLife: "1767-1824",
    sku: "AM-G-018",
    basePrice: 47561,
    currency: "AED",
    image: "/image/g/napoleon in coronation robes.jpg",
    options: [{ id: 'opt1', width: 256, height: 183.3, price: 47561, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Young Man As A Hunter",
    year: "1811",
    originalSize: "65 x 54.5 cm",
    artist: "Anne-Louis Girodet De Roussy-Trioson",
    artistLife: "1767-1824",
    sku: "AM-G-019",
    basePrice: 7160,
    currency: "AED",
    image: "/image/g/portrait of young man as a hunter.jpg",
    options: [{ id: 'opt1', width: 65, height: 54.5, price: 7160, label: 'Original Size' }],
  },

  {
    title: "Pygmalion And Galatea",
    year: "1813",
    originalSize: "253 x 202 cm",
    artist: "Anne-Louis Girodet De Roussy-Trioson",
    artistLife: "1767-1824",
    sku: "AM-G-020",
    basePrice: 28104,
    currency: "AED",
    image: "/image/g/pygmalion and galatea.jpg",
    options: [{ id: 'opt1', width: 253, height: 202, price: 28104, label: 'Original Size' }],
  },

  {
    title: "Van Gogh's Bedroom At Arles",
    year: "1889",
    originalSize: "57.5 x 74 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-021",
    basePrice: 2500,
    currency: "AED",
    image: "/image/g/van gogh's bedroom at aries.jpg",
    options: [{ id: 'opt1', width: 57.5, height: 74, price: 2500, label: 'Original Size' }],
  },

  {
    title: "Shoes",
    year: "1887",
    originalSize: "32.7 x 40.6 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-022",
    basePrice: 1672,
    currency: "AED",
    image: "/image/g/shoes.jpg",
    options: [{ id: 'opt1', width: 32.7, height: 40.6, price: 1672, label: 'Original Size' }],
  },

  {
    title: "Postman Joseph Roulin",
    year: "1888",
    originalSize: "81.3 x 65.4 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-023",
    basePrice: 2780,
    currency: "AED",
    image: "/image/g/postman joseph roulin.jpg",
    options: [{ id: 'opt1', width: 81.3, height: 65.4, price: 2780, label: 'Original Size' }],
  },

  {
    title: "Vase Of Roses",
    year: "1890",
    originalSize: "93 x 74 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-024",
    basePrice: 3525,
    currency: "AED",
    image: "/image/g/vase of roses.jpg",
    options: [{ id: 'opt1', width: 93, height: 74, price: 3525, label: 'Original Size' }],
  },

  {
    title: "Irises",
    year: "1889",
    originalSize: "71 x 93 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-025",
    basePrice: 4770,
    currency: "AED",
    image: "/image/g/irises.jpg",
    options: [{ id: 'opt1', width: 71, height: 93, price: 4770, label: 'Original Size' }],
  },

  {
    title: "Red Vineyards At Arles",
    year: "1888",
    originalSize: "73 x 91 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-026",
    basePrice: 3142,
    currency: "AED",
    image: "/image/g/red vineyards at airies.jpg",
    options: [{ id: 'opt1', width: 73, height: 91, price: 3142, label: 'Original Size' }],
  },

  {
    title: "Wheat Field With Crows 1890",
    year: "1890",
    originalSize: "50.5 x 103 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-027",
    basePrice: 2744,
    currency: "AED",
    image: "/image/g/wheat field with crows 1890.jpg",
    options: [{ id: 'opt1', width: 50.5, height: 103, price: 2744, label: 'Original Size' }],
  },

  {
    title: "Starry Night Over The Rhone",
    year: "1888",
    originalSize: "75.2 x 92 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-028",
    basePrice: 3145,
    currency: "AED",
    image: "/image/g/starry night over the rhone.jpg",
    options: [{ id: 'opt1', width: 75.2, height: 92, price: 3145, label: 'Original Size' }],
  },

  {
    title: "The Cafe Terrace On The Place Du Forum Arles",
    year: "1888",
    originalSize: "61 x 65.5 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-029",
    basePrice: 3989,
    currency: "AED",
    image: "/image/g/the cafe terrace on the place du forum airies.jpg",
    options: [{ id: 'opt1', width: 61, height: 65.5, price: 3989, label: 'Original Size' }],
  },

  {
    title: "Haystacks In Provence",
    year: "1888",
    originalSize: "73 x 92.5 cm",
    artist: "Vincent Van Gogh",
    artistLife: "1853-1890",
    sku: "AM-G-030",
    basePrice: 3145,
    currency: "AED",
    image: "/image/g/haystacks in provence.jpg",
    options: [{ id: 'opt1', width: 73, height: 92.5, price: 3145, label: 'Original Size' }],
  },

  {
    title: "Hampstead",
    year: "1881",
    originalSize: "34.3 x 44.5 cm",
    artist: "John Atkinson Grimshaw",
    artistLife: "1836-1893",
    sku: "AM-G-031",
    basePrice: 2999,
    currency: "AED",
    image: "/image/g/hampstead.jpg",
    options: [{ id: 'opt1', width: 34.3, height: 44.5, price: 2999, label: 'Original Size' }],
  },

  {
    title: "The Lady Of Shalott",
    year: "Unknown",
    originalSize: "61 x 76 cm",
    artist: "John Atkinson Grimshaw",
    artistLife: "1836-1893",
    sku: "AM-G-032",
    basePrice: 4772,
    currency: "AED",
    image: "/image/g/the lady of shalott.jpg",
    options: [{ id: 'opt1', width: 61, height: 76, price: 4772, label: 'Original Size' }],
  },

  {
    title: "London Bridge Half Tide",
    year: "1884",
    originalSize: "56 x 91 cm",
    artist: "John Atkinson Grimshaw",
    artistLife: "1836-1893",
    sku: "AM-G-033",
    basePrice: 5698,
    currency: "AED",
    image: "/image/g/london bridge half tide.jpg",
    options: [{ id: 'opt1', width: 56, height: 91, price: 5698, label: 'Original Size' }],
  },

  {
    title: "Liverpool From Wapping",
    year: "1885",
    originalSize: "61 x 93 cm",
    artist: "John Atkinson Grimshaw",
    artistLife: "1836-1893",
    sku: "AM-G-034",
    basePrice: 5480,
    currency: "AED",
    image: "/image/g/liverpool from wapping.jpg",
    options: [{ id: 'opt1', width: 61, height: 93, price: 5480, label: 'Original Size' }],
  },

