  {
    title: "Italian Landscape",
    year: "1795",
    originalSize: "64.5 x 96 cm",
    artist: "Jacob Philippe Hackett",
    artistLife: "1737-1807",
    sku: "AM-H-001",
    basePrice: 9091,
    currency: "AED",
    image: "/image/h/italian landscape.jpg",
    options: [{ id: 'opt1', width: 64.5, height: 96, price: 9091, label: 'Original Size' }],
  },

  {
    title: "View Of Copper Mill In Vietri",
    year: "1773",
    originalSize: "64 x 87 cm",
    artist: "Jacob Philippe Hackett",
    artistLife: "1737-1807",
    sku: "AM-H-002",
    basePrice: 9156,
    currency: "AED",
    image: "/image/h/view of copper mill in vietri.jpg",
    options: [{ id: 'opt1', width: 64, height: 87, price: 9156, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Young Man Holding A Glove",
    year: "1650",
    originalSize: "80 x 66.5 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-003",
    basePrice: 5454,
    currency: "AED",
    image: "/image/h/portrait of a young man holding a glove.jpg",
    options: [{ id: 'opt1', width: 80, height: 66.5, price: 5454, label: 'Original Size' }],
  },

  {
    title: "Married Couple In A Garden",
    year: "1622",
    originalSize: "70 x 83.25 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-004",
    basePrice: 21423,
    currency: "AED",
    image: "/image/h/married couple in a garden.jpg",
    options: [{ id: 'opt1', width: 70, height: 83.25, price: 21423, label: 'Original Size' }],
  },

  {
    title: "Laughing Cavallier",
    year: "1624",
    originalSize: "83 x 67 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-005",
    basePrice: 6741,
    currency: "AED",
    image: "/image/h/laughing cavallier.jpg",
    options: [{ id: 'opt1', width: 83, height: 67, price: 6741, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Man",
    year: "1660",
    originalSize: "91 x 66 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-006",
    basePrice: 6565,
    currency: "AED",
    image: "/image/h/portrait of a man.jpg",
    options: [{ id: 'opt1', width: 91, height: 66, price: 6565, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Woman",
    year: "1635",
    originalSize: "88 x 71 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-007",
    basePrice: 6938,
    currency: "AED",
    image: "/image/h/portrait of a woman.jpg",
    options: [{ id: 'opt1', width: 88, height: 71, price: 6938, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Elderly Man",
    year: "1627",
    originalSize: "81 x 71 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-008",
    basePrice: 6741,
    currency: "AED",
    image: "/image/h/portrait of a elderly man.jpg",
    options: [{ id: 'opt1', width: 81, height: 71, price: 6741, label: 'Original Size' }],
  },

  {
    title: "Malle Babbe",
    year: "1633",
    originalSize: "78.5 x 66.2 cm",
    artist: "Frans Hals",
    artistLife: "1582-1666",
    sku: "AM-H-009",
    basePrice: 4054,
    currency: "AED",
    image: "/image/h/malle babbe.jpg",
    options: [{ id: 'opt1', width: 78.5, height: 66.2, price: 4054, label: 'Original Size' }],
  },

  {
    title: "The Piebald Stallion At The Eisgruber Stud",
    year: "1700",
    originalSize: "101 x 81 cm",
    artist: "Johann Georg Von Hamilton",
    artistLife: "1672-1737",
    sku: "AM-H-010",
    basePrice: 8031,
    currency: "AED",
    image: "/image/h/the piebald stallion at the eisgruber stud.jpg",
    options: [{ id: 'opt1', width: 101, height: 81, price: 8031, label: 'Original Size' }],
  },

  {
    title: "A Black Horse Performing The Courbette",
    year: "Unknown",
    originalSize: "81 x 96 cm",
    artist: "Johann Georg Von Hamilton",
    artistLife: "1672-1737",
    sku: "AM-H-011",
    basePrice: 8597,
    currency: "AED",
    image: "/image/h/a black horse performing the courbette.jpg",
    options: [{ id: 'opt1', width: 81, height: 96, price: 8597, label: 'Original Size' }],
  },

  {
    title: "Rosslyn Chapel Near Edingburgh",
    year: "1860",
    originalSize: "50 x 40 cm",
    artist: "Heinrich Hansen",
    artistLife: "1821-1890",
    sku: "AM-H-012",
    basePrice: 10835,
    currency: "AED",
    image: "/image/h/rosslyn chapel near edingburgh.jpg",
    options: [{ id: 'opt1', width: 50, height: 40, price: 10835, label: 'Original Size' }],
  },

  {
    title: "George Glennie Putting At Blackheath With Putting Cleek",
    year: "1881",
    originalSize: "80 x 63 cm",
    artist: "Heywood Hardy",
    artistLife: "1843-1933",
    sku: "AM-H-013",
    basePrice: 5518,
    currency: "AED",
    image: "/image/h/george glennie putting at blackheath with putting cleek.jpg",
    options: [{ id: 'opt1', width: 80, height: 63, price: 5518, label: 'Original Size' }],
  },

  {
    title: "The Meet",
    year: "Unknown",
    originalSize: "51 x 79 cm",
    artist: "Heywood Hardy",
    artistLife: "1843-1933",
    sku: "AM-H-014",
    basePrice: 6260,
    currency: "AED",
    image: "/image/h/the meet.jpg",
    options: [{ id: 'opt1', width: 51, height: 79, price: 6260, label: 'Original Size' }],
  },

  {
    title: "Moonlight On The River",
    year: "1919",
    originalSize: "71 x 64 cm",
    artist: "Birge Harrison",
    artistLife: "1854-1929",
    sku: "AM-H-015",
    basePrice: 2195,
    currency: "AED",
    image: "/image/h/moonlight on the river.jpg",
    options: [{ id: 'opt1', width: 71, height: 64, price: 2195, label: 'Original Size' }],
  },

  {
    title: "Summer In The Catskills",
    year: "1865",
    originalSize: "33.5 x 59 cm",
    artist: "James McDougal Hart",
    artistLife: "1828-1901",
    sku: "AM-H-016",
    basePrice: 2272,
    currency: "AED",
    image: "/image/h/summer in the catskills.jpg",
    options: [{ id: 'opt1', width: 33.5, height: 59, price: 2272, label: 'Original Size' }],
  },

  {
    title: "New England Sea View Fish House",
    year: "1934",
    originalSize: "45.7 x 61 cm",
    artist: "Marsden Hartley",
    artistLife: "1877-1934",
    sku: "AM-H-017",
    basePrice: 2581,
    currency: "AED",
    image: "/image/h/new england sea view fish house.jpg",
    options: [{ id: 'opt1', width: 45.7, height: 61, price: 2581, label: 'Original Size' }],
  },

  {
    title: "The Aero",
    year: "1914",
    originalSize: "100.3 x 81.2 cm",
    artist: "Marsden Hartley",
    artistLife: "1877-1934",
    sku: "AM-H-018",
    basePrice: 4365,
    currency: "AED",
    image: "/image/h/the aero.jpg",
    options: [{ id: 'opt1', width: 100.3, height: 81.2, price: 4365, label: 'Original Size' }],
  },

  {
    title: "The Summer Camp Blue Mountain",
    year: "1909",
    originalSize: "70 x 90 cm",
    artist: "Marsden Hartley",
    artistLife: "1877-1934",
    sku: "AM-H-019",
    basePrice: 4687,
    currency: "AED",
    image: "/image/h/the summer camp blue mountain.jpg",
    options: [{ id: 'opt1', width: 70, height: 90, price: 4687, label: 'Original Size' }],
  },

  {
    title: "Newport Waterfront",
    year: "1901",
    originalSize: "66.6 x 61.4 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-020",
    basePrice: 2727,
    currency: "AED",
    image: "/image/h/newport waterfront.jpg",
    options: [{ id: 'opt1', width: 66.6, height: 61.4, price: 2727, label: 'Original Size' }],
  },

  {
    title: "An Outdoor Portrait Of Miss Weir",
    year: "1909",
    originalSize: "96.5 x 96.5 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-021",
    basePrice: 3128,
    currency: "AED",
    image: "/image/h/an outdoor portrait of miss weir.jpg",
    options: [{ id: 'opt1', width: 96.5, height: 96.5, price: 3128, label: 'Original Size' }],
  },

  {
    title: "Surf and Rocks",
    year: "1906",
    originalSize: "50.8 x 76.2 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-022",
    basePrice: 2534,
    currency: "AED",
    image: "/image/h/surf and rocks.jpg",
    options: [{ id: 'opt1', width: 50.8, height: 76.2, price: 2534, label: 'Original Size' }],
  },

  {
    title: "The Smelt Fishers, Cos Cob",
    year: "1996",
    originalSize: "54 x 44.5 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-023",
    basePrice: 1998,
    currency: "AED",
    image: "/image/h/the smelt fishers, cos cob.jpg",
    options: [{ id: 'opt1', width: 54, height: 44.5, price: 1998, label: 'Original Size' }],
  },

  {
    title: "The Table Garden",
    year: "1910",
    originalSize: "100.3 x 75.6 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-024",
    basePrice: 3674,
    currency: "AED",
    image: "/image/h/the table garden.jpg",
    options: [{ id: 'opt1', width: 100.3, height: 75.6, price: 3674, label: 'Original Size' }],
  },

  {
    title: "Oyster Sloop, Cos Cob",
    year: "1902",
    originalSize: "62 x 56.8 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-025",
    basePrice: 2388,
    currency: "AED",
    image: "/image/h/oyster sloop, cos cob.jpg",
    options: [{ id: 'opt1', width: 62, height: 56.8, price: 2388, label: 'Original Size' }],
  },

  {
    title: "The Victorian Chair",
    year: "1906",
    originalSize: "76.5 x 63.5 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-026",
    basePrice: 3331,
    currency: "AED",
    image: "/image/h/the victorian chair.jpg",
    options: [{ id: 'opt1', width: 76.5, height: 63.5, price: 3331, label: 'Original Size' }],
  },

  {
    title: "Twenty Sixth June Old Lyme",
    year: "1912",
    originalSize: "80.6 x 62.2 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-027",
    basePrice: 3519,
    currency: "AED",
    image: "/image/h/twenty sixth june old lyme.jpg",
    options: [{ id: 'opt1', width: 80.6, height: 62.2, price: 3519, label: 'Original Size' }],
  },

  {
    title: "Church At Old Lyme",
    year: "1905",
    originalSize: "92 x 82 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-028",
    basePrice: 3768,
    currency: "AED",
    image: "/image/h/church at old lyme.jpg",
    options: [{ id: 'opt1', width: 92, height: 82, price: 3768, label: 'Original Size' }],
  },

  {
    title: "The West Wind Isles Of Shoals",
    year: "1904",
    originalSize: "38 x 56 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-029",
    basePrice: 1817,
    currency: "AED",
    image: "/image/h/the west wind isles of shoals.jpg",
    options: [{ id: 'opt1', width: 38, height: 56, price: 1817, label: 'Original Size' }],
  },

  {
    title: "Duck Island from Appledore",
    year: "1911",
    originalSize: "71.8 x 90.8 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-030",
    basePrice: 3620,
    currency: "AED",
    image: "/image/h/duck island from appledore.jpg",
    options: [{ id: 'opt1', width: 71.8, height: 90.8, price: 3620, label: 'Original Size' }],
  },

  {
    title: "Central Park",
    year: "1892",
    originalSize: "45.7 x 57.2 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-031",
    basePrice: 2900,
    currency: "AED",
    image: "/image/h/central park.jpg",
    options: [{ id: 'opt1', width: 45.7, height: 57.2, price: 2900, label: 'Original Size' }],
  },

  {
    title: "Promenade At Sunset Paris",
    year: "1888",
    originalSize: "46 x 38.4 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-032",
    basePrice: 2382,
    currency: "AED",
    image: "/image/h/promenade at sunset paris.jpg",
    options: [{ id: 'opt1', width: 46, height: 38.4, price: 2382, label: 'Original Size' }],
  },

  {
    title: "The Spanish Stairs Rome",
    year: "1897",
    originalSize: "74.4 x 59.3 cm",
    artist: "Frederick Childe Hassam",
    artistLife: "1851-1935",
    sku: "AM-H-033",
    basePrice: 3423,
    currency: "AED",
    image: "/image/h/the spanish stairs rome.jpg",
    options: [{ id: 'opt1', width: 74.4, height: 59.3, price: 3423, label: 'Original Size' }],
  },

  {
    title: "Abraham Lincoln",
    year: "1869",
    originalSize: "100 x 76 cm",
    artist: "George Healy",
    artistLife: "1813-1894",
    sku: "AM-H-034",
    basePrice: 5424,
    currency: "AED",
    image: "/image/h/abraham lincoln.jpg",
    options: [{ id: 'opt1', width: 100, height: 76, price: 5424, label: 'Original Size' }],
  },

  {
    title: "The Three Masted Merchantman",
    year: "Unknown",
    originalSize: "50.8 x 80 cm",
    artist: "Joseph Heard",
    artistLife: "1799-1859",
    sku: "AM-H-035",
    basePrice: 4695,
    currency: "AED",
    image: "/image/h/the three masted merchantman.jpg",
    options: [{ id: 'opt1', width: 50.8, height: 80, price: 4695, label: 'Original Size' }],
  },

  {
    title: "The Great Wave Of Kanagawa",
    year: "1830",
    originalSize: "25.4 x 38 cm",
    artist: "Katsushika Hokusai",
    artistLife: "1760-1849",
    sku: "AM-H-036",
    basePrice: 2350,
    currency: "AED",
    image: "/image/h/the great wave of kanagawa.jpg",
    options: [{ id: 'opt1', width: 25.4, height: 38, price: 2350, label: 'Original Size' }],
  },

