export const iArtworks = [
  {
    title: "A Bit Of Roman Aqueduct",
    year: "1852",
    originalSize: "20.3 x 25.4 cm",
    artist: "George Inness",
    artistLife: "1830-1894",
    sku: "AM-I-001",
    basePrice: 2440,
    currency: "AED",
    image: "/image/i/a bit of roman aqueduct.jpg",
    options: [{ id: 'opt1', width: 20.3, height: 25.4, price: 2440, label: 'Original Size' }],
  },

  {
    title: "Autumn Oaks",
    year: "1878",
    originalSize: "54.3 x 76.5 cm",
    artist: "George Inness",
    artistLife: "1836-1894",
    sku: "AM-I-002",
    basePrice: 2500,
    currency: "AED",
    image: "/image/i/autumn oaks.jpg",
    options: [{ id: 'opt1', width: 54.3, height: 76.5, price: 2500, label: 'Original Size' }],
  },

  {
    title: "Children Of The Sea",
    year: "1872",
    originalSize: "48.5 x 93.5 cm",
    artist: "Jozef Israels",
    artistLife: "1825-1911",
    sku: "AM-I-003",
    basePrice: 3322,
    currency: "AED",
    image: "/image/i/children of the sea.jpg",
    options: [{ id: 'opt1', width: 48.5, height: 93.5, price: 3322, label: 'Original Size' }],
  },

  {
    title: "Domtesse D'Haussonvile",
    year: "1845",
    originalSize: "131.7 x 92 cm",
    artist: "Jean-August Dominique Ingres",
    artistLife: "1780-1867",
    sku: "AM-I-004",
    basePrice: 14992,
    currency: "AED",
    image: "/image/i/domtesse d'haussonvile.jpg",
    options: [{ id: 'opt1', width: 131.7, height: 92, price: 14992, label: 'Original Size' }],
  },

  {
    title: "Golden Glow (The Golden Sun)",
    year: "1894",
    originalSize: "61 x 91.4 cm",
    artist: "George Inness",
    artistLife: "1838-1894",
    sku: "AM-I-005",
    basePrice: 2440,
    currency: "AED",
    image: "/image/i/golden glow (the golden sun).jpg",
    options: [{ id: 'opt1', width: 61, height: 91.4, price: 2440, label: 'Original Size' }],
  },

  {
    title: "Hudson River Valley",
    year: "1867",
    originalSize: "61 x 87.6 cm",
    artist: "George Inness",
    artistLife: "1833-1894",
    sku: "AM-I-006",
    basePrice: 2650,
    currency: "AED",
    image: "/image/i/hudson river valley.jpg",
    options: [{ id: 'opt1', width: 61, height: 87.6, price: 2650, label: 'Original Size' }],
  },

  {
    title: "Landscape Sunset",
    year: "1889",
    originalSize: "56.3 x 91.8 cm",
    artist: "George Inness",
    artistLife: "1834-1894",
    sku: "AM-I-007",
    basePrice: 2685,
    currency: "AED",
    image: "/image/i/landscape sunset.jpg",
    options: [{ id: 'opt1', width: 56.3, height: 91.8, price: 2685, label: 'Original Size' }],
  },

  {
    title: "Landscape",
    year: "1848",
    originalSize: "74.9 x 113 cm",
    artist: "George Inness",
    artistLife: "1835-1894",
    sku: "AM-I-008",
    basePrice: 3614,
    currency: "AED",
    image: "/image/i/landscape.jpg",
    options: [{ id: 'opt1', width: 74.9, height: 113, price: 3614, label: 'Original Size' }],
  },

  {
    title: "Morning, Catskill Valley",
    year: "1894",
    originalSize: "91 x 122 cm",
    artist: "George Inness",
    artistLife: "1827-1894",
    sku: "AM-I-009",
    basePrice: 4475.74,
    currency: "AED",
    image: "/image/i/morning, catskill valley.jpg",
    options: [{ id: 'opt1', width: 91, height: 122, price: 4475.74, label: 'Original Size' }],
  },

  {
    title: "Sundown Near Montclair",
    year: "1885",
    originalSize: "51 x 66 cm",
    artist: "George Inness",
    artistLife: "1828-1894",
    sku: "AM-I-010",
    basePrice: 2068,
    currency: "AED",
    image: "/image/i/sundown near montclair.jpg",
    options: [{ id: 'opt1', width: 51, height: 66, price: 2068, label: 'Original Size' }],
  },

  {
    title: "The Clouded Sun",
    year: "1891",
    originalSize: "76.2 x 114.3 cm",
    artist: "George Inness",
    artistLife: "1825-1894",
    sku: "AM-I-011",
    basePrice: 5996,
    currency: "AED",
    image: "/image/i/the clouded sun.jpg",
    options: [{ id: 'opt1', width: 76.2, height: 114.3, price: 5996, label: 'Original Size' }],
  },

  {
    title: "The Home At Monclair",
    year: "1892",
    originalSize: "72.7 x 114.3 cm",
    artist: "George Inness",
    artistLife: "1826-1894",
    sku: "AM-I-012",
    basePrice: 5920,
    currency: "AED",
    image: "/image/i/the home at monclair.jpg",
    options: [{ id: 'opt1', width: 72.7, height: 114.3, price: 5920, label: 'Original Size' }],
  },

  {
    title: "Villa Borgese, Rome",
    year: "1857",
    originalSize: "10.8 x 17.8 cm",
    artist: "George Inness",
    artistLife: "1837-1894",
    sku: "AM-I-013",
    basePrice: 2500,
    currency: "AED",
    image: "/image/i/villa borgese, rome.jpg",
    options: [{ id: 'opt1', width: 10.8, height: 17.8, price: 2500, label: 'Original Size' }],
  },

];

export default iArtworks;
