export const kArtworks = [
  {
    title: "Blue Sky",
    year: "1940",
    originalSize: "100 x 73 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-001",
    basePrice: 6699,
    currency: "AED",
    image: "/image/k/blue sky.jpg",
    options: [{ id: 'opt1', width: 100, height: 73, price: 6699, label: 'Original Size' }],
  },

  {
    title: "Circles In A Circle",
    year: "1923",
    originalSize: "98.7 x 95.6 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-002",
    basePrice: 9159,
    currency: "AED",
    image: "/image/k/circles in a circle.jpg",
    options: [{ id: 'opt1', width: 98.7, height: 95.6, price: 9159, label: 'Original Size' }],
  },

  {
    title: "Composition 4",
    year: "1911",
    originalSize: "159.5 x 250.5 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-003",
    basePrice: 44124,
    currency: "AED",
    image: "/image/k/composition 4.jpg",
    options: [{ id: 'opt1', width: 159.5, height: 250.5, price: 44124, label: 'Original Size' }],
  },

  {
    title: "Composition 8",
    year: "1923",
    originalSize: "140 x 201 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-004",
    basePrice: 30324,
    currency: "AED",
    image: "/image/k/composition 8.jpg",
    options: [{ id: 'opt1', width: 140, height: 201, price: 30324, label: 'Original Size' }],
  },

  {
    title: "Composition IX",
    year: "1936",
    originalSize: "113.5 x 195 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-005",
    basePrice: 23844,
    currency: "AED",
    image: "/image/k/composition IX.jpg",
    options: [{ id: 'opt1', width: 113.5, height: 195, price: 23844, label: 'Original Size' }],
  },

  {
    title: "Concentric Circles",
    year: "1913",
    originalSize: "47.5 x 49.5 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-006",
    basePrice: 2460,
    currency: "AED",
    image: "/image/k/concentric circles.jpg",
    options: [{ id: 'opt1', width: 47.5, height: 49.5, price: 2460, label: 'Original Size' }],
  },

  {
    title: "Danae",
    year: "1907",
    originalSize: "77 x 83 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-007",
    basePrice: 6774,
    currency: "AED",
    image: "/image/k/danae.jpg",
    options: [{ id: 'opt1', width: 77, height: 83, price: 6774, label: 'Original Size' }],
  },

  {
    title: "Far Far Away Soria Moria Palace Shimmered Like Gold",
    year: "1900",
    originalSize: "58 x 87 cm",
    artist: "Theodor Kittelsen",
    artistLife: "1857-1914",
    sku: "AM-K-008",
    basePrice: 5112,
    currency: "AED",
    image: "/image/k/far far away soria moria palace shimmered like gold.jpg",
    options: [{ id: 'opt1', width: 58, height: 87, price: 5112, label: 'Original Size' }],
  },

  {
    title: "Girl Friends",
    year: "1928",
    originalSize: "60 x 73 cm",
    artist: "Moise Kisling",
    artistLife: "1891-1953",
    sku: "AM-K-009",
    basePrice: 4464,
    currency: "AED",
    image: "/image/k/girl friends.jpg",
    options: [{ id: 'opt1', width: 60, height: 73, price: 4464, label: 'Original Size' }],
  },

  {
    title: "Gold Fish",
    year: "1901",
    originalSize: "150 x 46 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-010",
    basePrice: 7284,
    currency: "AED",
    image: "/image/k/gold fish.jpg",
    options: [{ id: 'opt1', width: 150, height: 46, price: 7284, label: 'Original Size' }],
  },

  {
    title: "Hip Hip Hooray, Artist Festival At Skagen",
    year: "1888",
    originalSize: "134.5 x 165.5 cm",
    artist: "Peder Severin Kroyer",
    artistLife: "1851-1909",
    sku: "AM-K-011",
    basePrice: 23988,
    currency: "AED",
    image: "/image/k/hip hip hooray, artist festival at skagen.jpg",
    options: [{ id: 'opt1', width: 134.5, height: 165.5, price: 23988, label: 'Original Size' }],
  },

  {
    title: "Hope II",
    year: "1907",
    originalSize: "110.5 x 110.5 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-012",
    basePrice: 13164,
    currency: "AED",
    image: "/image/k/hope II.jpg",
    options: [{ id: 'opt1', width: 110.5, height: 110.5, price: 13164, label: 'Original Size' }],
  },

  {
    title: "Judith I",
    year: "1901",
    originalSize: "84 x 42 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-013",
    basePrice: 3792,
    currency: "AED",
    image: "/image/k/judith I.jpg",
    options: [{ id: 'opt1', width: 84, height: 42, price: 3792, label: 'Original Size' }],
  },

  {
    title: "Moscow I",
    year: "1916",
    originalSize: "51.5 x 49.5 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-014",
    basePrice: 2604,
    currency: "AED",
    image: "/image/k/moscow I.jpg",
    options: [{ id: 'opt1', width: 51.5, height: 49.5, price: 2604, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Man With Streimel",
    year: "Unknown",
    originalSize: "35.5 x 26 cm",
    artist: "Isidor Kaufmann",
    artistLife: "1853-1921",
    sku: "AM-K-015",
    basePrice: 984,
    currency: "AED",
    image: "/image/k/portrait of a man with streimel.jpg",
    options: [{ id: 'opt1', width: 35.5, height: 26, price: 984, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Rabbi",
    year: "1910",
    originalSize: "26 x 35.5 cm",
    artist: "Isidor Kaufmann",
    artistLife: "1853-1921",
    sku: "AM-K-016",
    basePrice: 984,
    currency: "AED",
    image: "/image/k/portrait of a rabbi.jpg",
    options: [{ id: 'opt1', width: 26, height: 35.5, price: 984, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Young Boy With Peyot",
    year: "Unknown",
    originalSize: "35.5 x 26 cm",
    artist: "Isidor Kaufmann",
    artistLife: "1853-1921",
    sku: "AM-K-017",
    basePrice: 984,
    currency: "AED",
    image: "/image/k/portrait of a young boy with peyot.jpg",
    options: [{ id: 'opt1', width: 35.5, height: 26, price: 984, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Adele Bloch-Bauer I",
    year: "1907",
    originalSize: "138 x 138 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-018",
    basePrice: 20532,
    currency: "AED",
    image: "/image/k/portrait of adele bloch-bauer I.jpg",
    options: [{ id: 'opt1', width: 138, height: 138, price: 20532, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Eugeina Primavesi",
    year: "1913",
    originalSize: "140 x 84 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-019",
    basePrice: 12684,
    currency: "AED",
    image: "/image/k/portrait of eugeina primavesi.jpg",
    options: [{ id: 'opt1', width: 140, height: 84, price: 12684, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Fritza Riedlar",
    year: "1906",
    originalSize: "153 x 133 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-020",
    basePrice: 21936,
    currency: "AED",
    image: "/image/k/portrait of fritza riedlar.jpg",
    options: [{ id: 'opt1', width: 153, height: 133, price: 21936, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Johanna Straude",
    year: "1917",
    originalSize: "70 x 50 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-021",
    basePrice: 3744,
    currency: "AED",
    image: "/image/k/portrait of johanna straude.jpg",
    options: [{ id: 'opt1', width: 70, height: 50, price: 3744, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Wolfang Amadeus Mozart",
    year: "1819",
    originalSize: "54.5 x 44 cm",
    artist: "Barbara Krafft",
    artistLife: "1764-1825",
    sku: "AM-K-022",
    basePrice: 2484,
    currency: "AED",
    image: "/image/k/portrait of wolfang amadeus mozart.jpg",
    options: [{ id: 'opt1', width: 54.5, height: 44, price: 2484, label: 'Original Size' }],
  },

  {
    title: "Shubert At The Piano",
    year: "1899",
    originalSize: "150 x 200 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-023",
    basePrice: 32304,
    currency: "AED",
    image: "/image/k/shubert at the piano.jpg",
    options: [{ id: 'opt1', width: 150, height: 200, price: 32304, label: 'Original Size' }],
  },

  {
    title: "Signs In Yellow",
    year: "1933",
    originalSize: "60 x 50 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-024",
    basePrice: 3216,
    currency: "AED",
    image: "/image/k/signs in yellow.jpg",
    options: [{ id: 'opt1', width: 60, height: 50, price: 3216, label: 'Original Size' }],
  },

  {
    title: "Sir Christopher Wren",
    year: "1711",
    originalSize: "123 x 99 cm",
    artist: "Godfrey Kneller",
    artistLife: "1646-1723",
    sku: "AM-K-025",
    basePrice: 13104,
    currency: "AED",
    image: "/image/k/sir christopher wren.jpg",
    options: [{ id: 'opt1', width: 123, height: 99, price: 13104, label: 'Original Size' }],
  },

  {
    title: "Still Life With Drinking Horn",
    year: "1653",
    originalSize: "86 x 102 cm",
    artist: "Willem Kalf",
    artistLife: "1619-1693",
    sku: "AM-K-026",
    basePrice: 9444,
    currency: "AED",
    image: "/image/k/still life with drinking horn.jpg",
    options: [{ id: 'opt1', width: 86, height: 102, price: 9444, label: 'Original Size' }],
  },

  {
    title: "Still Life With Fruit In A Wan-Li Bowl",
    year: "Unknown",
    originalSize: "65 x 55 cm",
    artist: "Willem Kalf",
    artistLife: "1619-1693",
    sku: "AM-K-027",
    basePrice: 3840,
    currency: "AED",
    image: "/image/k/still life with fruit in a wan-li bowl.jpg",
    options: [{ id: 'opt1', width: 65, height: 55, price: 3840, label: 'Original Size' }],
  },

  {
    title: "The Kiss",
    year: "1908",
    originalSize: "180 x 180 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-028",
    basePrice: 34920,
    currency: "AED",
    image: "/image/k/the kiss.jpg",
    options: [{ id: 'opt1', width: 180, height: 180, price: 34920, label: 'Original Size' }],
  },

  {
    title: "The Promernade",
    year: "1917",
    originalSize: "170 x 163.5 cm",
    artist: "Marc Chagall",
    artistLife: "1887-1985",
    sku: "AM-K-029",
    basePrice: 29964,
    currency: "AED",
    image: "/image/k/the promernade.jpg",
    options: [{ id: 'opt1', width: 170, height: 163.5, price: 29964, label: 'Original Size' }],
  },

  {
    title: "The Three Ages Of Women",
    year: "1905",
    originalSize: "180 x 180 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-030",
    basePrice: 34920,
    currency: "AED",
    image: "/image/k/the three ages of women.jpg",
    options: [{ id: 'opt1', width: 180, height: 180, price: 34920, label: 'Original Size' }],
  },

  {
    title: "The Tree Of Life",
    year: "1909",
    originalSize: "195 x 102 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-031",
    basePrice: 21444,
    currency: "AED",
    image: "/image/k/the tree of life.jpg",
    options: [{ id: 'opt1', width: 195, height: 102, price: 21444, label: 'Original Size' }],
  },

  {
    title: "Untitled (Transition)",
    year: "1934",
    originalSize: "60 x 50 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-032",
    basePrice: 3216,
    currency: "AED",
    image: "/image/k/untitled (transition).jpg",
    options: [{ id: 'opt1', width: 60, height: 50, price: 3216, label: 'Original Size' }],
  },

  {
    title: "Upward",
    year: "1929",
    originalSize: "70 x 49 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-033",
    basePrice: 3696,
    currency: "AED",
    image: "/image/k/upward.jpg",
    options: [{ id: 'opt1', width: 70, height: 49, price: 3696, label: 'Original Size' }],
  },

  {
    title: "Water Serpents",
    year: "1904",
    originalSize: "50 x 20 cm",
    artist: "Gustav Klimt",
    artistLife: "1862-1918",
    sku: "AM-K-034",
    basePrice: 1068,
    currency: "AED",
    image: "/image/k/water serpents.jpg",
    options: [{ id: 'opt1', width: 50, height: 20, price: 1068, label: 'Original Size' }],
  },

  {
    title: "Winter Landscape (1)",
    year: "1909",
    originalSize: "75.5 x 97.5 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-035",
    basePrice: 7944,
    currency: "AED",
    image: "/image/k/winter landscape (1).jpg",
    options: [{ id: 'opt1', width: 75.5, height: 97.5, price: 7944, label: 'Original Size' }],
  },

  {
    title: "Winter Landscape",
    year: "1909",
    originalSize: "75.5 x 97.5 cm",
    artist: "Wassily Kandinsky",
    artistLife: "1866-1944",
    sku: "AM-K-036",
    basePrice: 7944,
    currency: "AED",
    image: "/image/k/winter landscape.jpg",
    options: [{ id: 'opt1', width: 75.5, height: 97.5, price: 7944, label: 'Original Size' }],
  },

];

export default kArtworks;
