export const lArtworks = [
  {
    title: "A Boat On The Marne",
    year: "1905",
    originalSize: "65.2 x 92 cm",
    artist: "Henri Lebasque",
    artistLife: "1865-1937",
    sku: "AM-L-001",
    basePrice: 2809,
    currency: "AED",
    image: "/image/l/a boat on the marne.jpg",
    options: [{ id: 'opt1', width: 65.2, height: 92, price: 2809, label: 'Original Size' }],
  },

  {
    title: "A Favorite Greyhound Of Prince Albert",
    year: "1841",
    originalSize: "11.8 x 142.9 cm",
    artist: "Sir Edwin Henry Landseer",
    artistLife: "1802-1873",
    sku: "AM-L-002",
    basePrice: 8125,
    currency: "AED",
    image: "/image/l/a favorite greyhound of prince albert.jpg",
    options: [{ id: 'opt1', width: 11.8, height: 142.9, price: 8125, label: 'Original Size' }],
  },

  {
    title: "Children In The Meadow",
    year: "1906",
    originalSize: "54 x 65.5 cm",
    artist: "Henri Lebasque",
    artistLife: "1865-1937",
    sku: "AM-L-003",
    basePrice: 2099,
    currency: "AED",
    image: "/image/l/children in the meadow.jpg",
    options: [{ id: 'opt1', width: 54, height: 65.5, price: 2099, label: 'Original Size' }],
  },

  {
    title: "Chloe",
    year: "1875",
    originalSize: "260 x 139 cm",
    artist: "Jules Joseph Lefebvre",
    artistLife: "1836-1911",
    sku: "AM-L-004",
    basePrice: 6630,
    currency: "AED",
    image: "/image/l/chloe.jpg",
    options: [{ id: 'opt1', width: 260, height: 139, price: 6630, label: 'Original Size' }],
  },

  {
    title: "Flaming June",
    year: "1895",
    originalSize: "120.6 x 120.6 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-005",
    basePrice: 9400,
    currency: "AED",
    image: "/image/l/flaming june.jpg",
    options: [{ id: 'opt1', width: 120.6, height: 120.6, price: 9400, label: 'Original Size' }],
  },

  {
    title: "Hhareem Life Constantinople",
    year: "1857",
    originalSize: "47.5 x 30.5 cm",
    artist: "John Frederick Lewis",
    artistLife: "1805-1876",
    sku: "AM-L-006",
    basePrice: 5773,
    currency: "AED",
    image: "/image/l/hhareem life constantinople.jpg",
    options: [{ id: 'opt1', width: 47.5, height: 30.5, price: 5773, label: 'Original Size' }],
  },

  {
    title: "Monarch Of The Glen",
    year: "1851",
    originalSize: "163.8 x 169 cm",
    artist: "Sir Edwin Henry Landseer",
    artistLife: "1802-1873",
    sku: "AM-L-007",
    basePrice: 10451,
    currency: "AED",
    image: "/image/l/monarch of the glen.jpg",
    options: [{ id: 'opt1', width: 163.8, height: 169, price: 10451, label: 'Original Size' }],
  },

  {
    title: "Mrs James Guthrie",
    year: "1864",
    originalSize: "210.7 x 138.5 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-008",
    basePrice: 7676,
    currency: "AED",
    image: "/image/l/mrs james guthrie.jpg",
    options: [{ id: 'opt1', width: 210.7, height: 138.5, price: 7676, label: 'Original Size' }],
  },

  {
    title: "Nude Lying",
    year: "Unknown",
    originalSize: "46.5 x 73 cm",
    artist: "Henri Lebasque",
    artistLife: "1865-1937",
    sku: "AM-L-009",
    basePrice: 2634,
    currency: "AED",
    image: "/image/l/nude lying.jpg",
    options: [{ id: 'opt1', width: 46.5, height: 73, price: 2634, label: 'Original Size' }],
  },

  {
    title: "Pavonia",
    year: "1859",
    originalSize: "53.3 x 42 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-010",
    basePrice: 4084,
    currency: "AED",
    image: "/image/l/pavonia.jpg",
    options: [{ id: 'opt1', width: 53.3, height: 42, price: 4084, label: 'Original Size' }],
  },

  {
    title: "Phoebe",
    year: "Unknown",
    originalSize: "56 x 61 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-011",
    basePrice: 4084,
    currency: "AED",
    image: "/image/l/phoebe.jpg",
    options: [{ id: 'opt1', width: 56, height: 61, price: 4084, label: 'Original Size' }],
  },

  {
    title: "Portrait Of Eugine-Louis-Napoleon Bonaparte",
    year: "1874",
    originalSize: "61 x 46 cm",
    artist: "Jules Joseph Lefebvre",
    artistLife: "1836-1911",
    sku: "AM-L-012",
    basePrice: 3748,
    currency: "AED",
    image: "/image/l/portrait of eugine-louis-napoleon bonaparte.jpg",
    options: [{ id: 'opt1', width: 61, height: 46, price: 3748, label: 'Original Size' }],
  },

  {
    title: "The Fisherman And The Syren",
    year: "1867",
    originalSize: "66.4 x 49 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-013",
    basePrice: 4691,
    currency: "AED",
    image: "/image/l/the fisherman and the syren.jpg",
    options: [{ id: 'opt1', width: 66.4, height: 49, price: 4691, label: 'Original Size' }],
  },

  {
    title: "The Grasshopper",
    year: "1872",
    originalSize: "186.7 x 123.8 cm",
    artist: "Jules Joseph Lefebvre",
    artistLife: "1836-1911",
    sku: "AM-L-014",
    basePrice: 6303,
    currency: "AED",
    image: "/image/l/the grasshopper.jpg",
    options: [{ id: 'opt1', width: 186.7, height: 123.8, price: 6303, label: 'Original Size' }],
  },

  {
    title: "The Green Coat",
    year: "1926",
    originalSize: "198.4 x 107.8 cm",
    artist: "Sir John Lavery",
    artistLife: "1856-1941",
    sku: "AM-L-015",
    basePrice: 22043,
    currency: "AED",
    image: "/image/l/the green coat.jpg",
    options: [{ id: 'opt1', width: 198.4, height: 107.8, price: 22043, label: 'Original Size' }],
  },

  {
    title: "The Japanese Bathrobe",
    year: "1926",
    originalSize: "61 x 50.3 cm",
    artist: "Henri Lebasque",
    artistLife: "1865-1937",
    sku: "AM-L-016",
    basePrice: 2019,
    currency: "AED",
    image: "/image/l/the japanese bathrobe.jpg",
    options: [{ id: 'opt1', width: 61, height: 50.3, price: 2019, label: 'Original Size' }],
  },

  {
    title: "The Nymph Of The River",
    year: "1880",
    originalSize: "76.8 x 27.2 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-017",
    basePrice: 4387,
    currency: "AED",
    image: "/image/l/the nymph of the river.jpg",
    options: [{ id: 'opt1', width: 76.8, height: 27.2, price: 4387, label: 'Original Size' }],
  },

  {
    title: "The Painters Honeymoon",
    year: "1864",
    originalSize: "83.8 x 76.8 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-018",
    basePrice: 5259,
    currency: "AED",
    image: "/image/l/the painters honeymoon.jpg",
    options: [{ id: 'opt1', width: 83.8, height: 76.8, price: 5259, label: 'Original Size' }],
  },

  {
    title: "The Resting In Saint Tropez",
    year: "1906",
    originalSize: "88.8 x 115.8 cm",
    artist: "Henri Lebasque",
    artistLife: "1865-1937",
    sku: "AM-L-019",
    basePrice: 3500,
    currency: "AED",
    image: "/image/l/the resting in saint tropez.jpg",
    options: [{ id: 'opt1', width: 88.8, height: 115.8, price: 3500, label: 'Original Size' }],
  },

  {
    title: "The Roman Lady (La Nana)",
    year: "1858",
    originalSize: "80 x 52.1 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-020",
    basePrice: 5118,
    currency: "AED",
    image: "/image/l/the roman lady (la nana).jpg",
    options: [{ id: 'opt1', width: 80, height: 52.1, price: 5118, label: 'Original Size' }],
  },

  {
    title: "There's No Place Like Home",
    year: "Unknown",
    originalSize: "60 x 70 cm",
    artist: "Sir Edwin Henry Landseer",
    artistLife: "1802-1873",
    sku: "AM-L-021",
    basePrice: 4532,
    currency: "AED",
    image: "/image/l/there's no place like home.jpg",
    options: [{ id: 'opt1', width: 60, height: 70, price: 4532, label: 'Original Size' }],
  },

  {
    title: "Wedded",
    year: "1882",
    originalSize: "145.4 x 81.3 cm",
    artist: "Lord Frederick Leighton",
    artistLife: "1830-1896",
    sku: "AM-L-022",
    basePrice: 6607,
    currency: "AED",
    image: "/image/l/wedded.jpg",
    options: [{ id: 'opt1', width: 145.4, height: 81.3, price: 6607, label: 'Original Size' }],
  },

];

export default lArtworks;
