export const mArtworks = [
  {
    title: "The Son Of Man",
    year: "1964",
    originalSize: "116 x 89 cm",
    artist: "Rene Magritte",
    artistLife: "1898-1964",
    sku: "AM-M-001",
    basePrice: 3985,
    currency: "AED",
    image: "/image/m/the son of man.jpg",
    options: [{ id: 'opt1', width: 116, height: 89, price: 3985, label: 'Original Size' }],
  },

  {
    title: "Man In A Bowler Hat",
    year: "1964",
    originalSize: "63.5 x 48 cm",
    artist: "Rene Magritte",
    artistLife: "1898-1964",
    sku: "AM-M-002",
    basePrice: 2920,
    currency: "AED",
    image: "/image/m/man in a bowler hat.jpg",
    options: [{ id: 'opt1', width: 63.5, height: 48, price: 2920, label: 'Original Size' }],
  },

  {
    title: "The Gold Weigher",
    year: "1670",
    originalSize: "81.5 x 67.5 cm",
    artist: "Cornelis de Man",
    artistLife: "1621-1706",
    sku: "AM-M-003",
    basePrice: 12277,
    currency: "AED",
    image: "/image/m/the gold weigher.jpg",
    options: [{ id: 'opt1', width: 81.5, height: 67.5, price: 12277, label: 'Original Size' }],
  },

  {
    title: "Olympia",
    year: "1863",
    originalSize: "130 x 190 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-004",
    basePrice: 5880,
    currency: "AED",
    image: "/image/m/olympia.jpg",
    options: [{ id: 'opt1', width: 130, height: 190, price: 5880, label: 'Original Size' }],
  },

  {
    title: "Oysters",
    year: "1862",
    originalSize: "39.1 x 46.7 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-005",
    basePrice: 2420,
    currency: "AED",
    image: "/image/m/oysters.jpg",
    options: [{ id: 'opt1', width: 39.1, height: 46.7, price: 2420, label: 'Original Size' }],
  },

  {
    title: "Still Life With Melon And Peaches",
    year: "1866",
    originalSize: "69 x 92.2 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-006",
    basePrice: 4075,
    currency: "AED",
    image: "/image/m/still life with melon and peaches.jpg",
    options: [{ id: 'opt1', width: 69, height: 92.2, price: 4075, label: 'Original Size' }],
  },

  {
    title: "Plum Brandy",
    year: "1878",
    originalSize: "73.6 x 50.2 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-007",
    basePrice: 3096,
    currency: "AED",
    image: "/image/m/plum brandy.jpg",
    options: [{ id: 'opt1', width: 73.6, height: 50.2, price: 3096, label: 'Original Size' }],
  },

  {
    title: "Masked Ball At The Opera",
    year: "1873",
    originalSize: "59 x 72.5 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-008",
    basePrice: 7824,
    currency: "AED",
    image: "/image/m/masked ball at the opera.jpg",
    options: [{ id: 'opt1', width: 59, height: 72.5, price: 7824, label: 'Original Size' }],
  },

  {
    title: "Boating",
    year: "1874",
    originalSize: "97.2 x 130.2 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-009",
    basePrice: 6756,
    currency: "AED",
    image: "/image/m/boating.jpg",
    options: [{ id: 'opt1', width: 97.2, height: 130.2, price: 6756, label: 'Original Size' }],
  },

  {
    title: "The Monet Family In Their Garden At Argenteuil",
    year: "1874",
    originalSize: "61 x 99.7 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-010",
    basePrice: 3716,
    currency: "AED",
    image: "/image/m/the monet family in their garden at argenteuil.jpg",
    options: [{ id: 'opt1', width: 61, height: 99.7, price: 3716, label: 'Original Size' }],
  },

  {
    title: "The Grand Canal Venice",
    year: "1874",
    originalSize: "57 x 48 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-011",
    basePrice: 3908,
    currency: "AED",
    image: "/image/m/the grand canal venice.jpg",
    options: [{ id: 'opt1', width: 57, height: 48, price: 3908, label: 'Original Size' }],
  },

  {
    title: "The Grand Canal (Blue Venice)",
    year: "1874",
    originalSize: "50 x 71 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-012",
    basePrice: 3301,
    currency: "AED",
    image: "/image/m/the grand canal (blue venice).jpg",
    options: [{ id: 'opt1', width: 50, height: 71, price: 3301, label: 'Original Size' }],
  },

  {
    title: "The Brioche",
    year: "1870",
    originalSize: "65.1 x 81 cm",
    artist: "Edouard Manet",
    artistLife: "1832-1883",
    sku: "AM-M-013",
    basePrice: 4366,
    currency: "AED",
    image: "/image/m/the brioche.jpg",
    options: [{ id: 'opt1', width: 65.1, height: 81, price: 4366, label: 'Original Size' }],
  },

  {
    title: "Stanczyk",
    year: "1862",
    originalSize: "88 x 120 cm",
    artist: "Jan Matejko",
    artistLife: "1838-1893",
    sku: "AM-M-014",
    basePrice: 8659,
    currency: "AED",
    image: "/image/m/stanczyk.jpg",
    options: [{ id: 'opt1', width: 88, height: 120, price: 8659, label: 'Original Size' }],
  },

  {
    title: "The Dance",
    year: "1909",
    originalSize: "150 x 230 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-015",
    basePrice: 7150,
    currency: "AED",
    image: "/image/m/the dance.jpg",
    options: [{ id: 'opt1', width: 150, height: 230, price: 7150, label: 'Original Size' }],
  },

  {
    title: "The Red Room, Harmony In Red",
    year: "1908",
    originalSize: "180 x 220 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-016",
    basePrice: 8120,
    currency: "AED",
    image: "/image/m/the red room, harmony in red.jpg",
    options: [{ id: 'opt1', width: 180, height: 220, price: 8120, label: 'Original Size' }],
  },

  {
    title: "Goldfish",
    year: "1912",
    originalSize: "147 x 98 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-017",
    basePrice: 4500,
    currency: "AED",
    image: "/image/m/goldfish.jpg",
    options: [{ id: 'opt1', width: 147, height: 98, price: 4500, label: 'Original Size' }],
  },

  {
    title: "Interior With Phonograph",
    year: "1927",
    originalSize: "100.5 x 80 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-018",
    basePrice: 3028,
    currency: "AED",
    image: "/image/m/interior with phonograph.jpg",
    options: [{ id: 'opt1', width: 100.5, height: 80, price: 3028, label: 'Original Size' }],
  },

  {
    title: "Arabian Coffee House",
    year: "1913",
    originalSize: "176 x 210 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-019",
    basePrice: 2270,
    currency: "AED",
    image: "/image/m/arabian coffee house.jpg",
    options: [{ id: 'opt1', width: 176, height: 210, price: 2270, label: 'Original Size' }],
  },

  {
    title: "Pink Statuette On The Red Chest",
    year: "1910",
    originalSize: "90 x 117 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-020",
    basePrice: 3290,
    currency: "AED",
    image: "/image/m/pink statuette on the red chest.jpg",
    options: [{ id: 'opt1', width: 90, height: 117, price: 3290, label: 'Original Size' }],
  },

  {
    title: "Spanish Still Life",
    year: "1910",
    originalSize: "89.5 x 116 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-021",
    basePrice: 4500,
    currency: "AED",
    image: "/image/m/spanish still life.jpg",
    options: [{ id: 'opt1', width: 89.5, height: 116, price: 4500, label: 'Original Size' }],
  },

  {
    title: "Still Life Of Fruit and Bronze Statue",
    year: "1910",
    originalSize: "91 x 118.3 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-022",
    basePrice: 4200,
    currency: "AED",
    image: "/image/m/still life of fruit and bronze statue.jpg",
    options: [{ id: 'opt1', width: 91, height: 118.3, price: 4200, label: 'Original Size' }],
  },

  {
    title: "Music",
    year: "1910",
    originalSize: "81 x 123 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-023",
    basePrice: 3220,
    currency: "AED",
    image: "/image/m/music.jpg",
    options: [{ id: 'opt1', width: 81, height: 123, price: 3220, label: 'Original Size' }],
  },

  {
    title: "A Game Of Bowls",
    year: "1908",
    originalSize: "115 x 147 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-024",
    basePrice: 4092,
    currency: "AED",
    image: "/image/m/a game of bowls.jpg",
    options: [{ id: 'opt1', width: 115, height: 147, price: 4092, label: 'Original Size' }],
  },

  {
    title: "Woman In Purple Coat Print",
    year: "1937",
    originalSize: "81 x 65.2 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-025",
    basePrice: 12829,
    currency: "AED",
    image: "/image/m/woman in purple coat print.jpg",
    options: [{ id: 'opt1', width: 81, height: 65.2, price: 12829, label: 'Original Size' }],
  },

  {
    title: "The Joy Of Life",
    year: "1906",
    originalSize: "176.5 x 240.7 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-026",
    basePrice: 16704,
    currency: "AED",
    image: "/image/m/the joy of life.jpg",
    options: [{ id: 'opt1', width: 176.5, height: 240.7, price: 16704, label: 'Original Size' }],
  },

  {
    title: "Still Life With Blue Tablecloth",
    year: "1909",
    originalSize: "88.5 x 116 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-027",
    basePrice: 3328,
    currency: "AED",
    image: "/image/m/still life with blue tablecloth.jpg",
    options: [{ id: 'opt1', width: 88.5, height: 116, price: 3328, label: 'Original Size' }],
  },

  {
    title: "Nymph and Satyr",
    year: "1908",
    originalSize: "89 x 117 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-028",
    basePrice: 3563,
    currency: "AED",
    image: "/image/m/nymph and satyr.jpg",
    options: [{ id: 'opt1', width: 89, height: 117, price: 3563, label: 'Original Size' }],
  },

  {
    title: "Lady In Green With A Red Carnation",
    year: "1909",
    originalSize: "65 x 54 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-029",
    basePrice: 2741,
    currency: "AED",
    image: "/image/m/lady in green with a red carnation.jpg",
    options: [{ id: 'opt1', width: 65, height: 54, price: 2741, label: 'Original Size' }],
  },

  {
    title: "Woman With A Hat",
    year: "1905",
    originalSize: "80.6 x 59.7 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-030",
    basePrice: 2835,
    currency: "AED",
    image: "/image/m/woman with a hat.jpg",
    options: [{ id: 'opt1', width: 80.6, height: 59.7, price: 2835, label: 'Original Size' }],
  },

  {
    title: "The Window",
    year: "1916",
    originalSize: "146.1 x 116.8 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-031",
    basePrice: 4099,
    currency: "AED",
    image: "/image/m/the window.jpg",
    options: [{ id: 'opt1', width: 146.1, height: 116.8, price: 4099, label: 'Original Size' }],
  },

  {
    title: "Nude In The Studio",
    year: "1899",
    originalSize: "46 x 60 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-032",
    basePrice: 3895,
    currency: "AED",
    image: "/image/m/nude in the studio.jpg",
    options: [{ id: 'opt1', width: 46, height: 60, price: 3895, label: 'Original Size' }],
  },

  {
    title: "The Green Line",
    year: "1905",
    originalSize: "40.5 x 32.5 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-033",
    basePrice: 2920,
    currency: "AED",
    image: "/image/m/the green line.jpg",
    options: [{ id: 'opt1', width: 40.5, height: 32.5, price: 2920, label: 'Original Size' }],
  },

  {
    title: "Corner Of The Artists Studio",
    year: "1912",
    originalSize: "191.5 x 114 cm",
    artist: "Henri Matisse",
    artistLife: "1869-1954",
    sku: "AM-M-034",
    basePrice: 17142,
    currency: "AED",
    image: "/image/m/corner of the artists studio.jpg",
    options: [{ id: 'opt1', width: 191.5, height: 114, price: 17142, label: 'Original Size' }],
  },

  {
    title: "Composition With Red Yellow Green",
    year: "1930",
    originalSize: "59.5 x 59.5 cm",
    artist: "Piet Mondrian",
    artistLife: "1872-1944",
    sku: "AM-M-035",
    basePrice: 1403,
    currency: "AED",
    image: "/image/m/composition with red yellow green.jpg",
    options: [{ id: 'opt1', width: 59.5, height: 59.5, price: 1403, label: 'Original Size' }],
  },

  {
    title: "Composition In Black And White",
    year: "1915",
    originalSize: "85 x 110 cm",
    artist: "Piet Mondrian",
    artistLife: "1872-1944",
    sku: "AM-M-036",
    basePrice: 3182,
    currency: "AED",
    image: "/image/m/composition in black and white.jpg",
    options: [{ id: 'opt1', width: 85, height: 110, price: 3182, label: 'Original Size' }],
  },

  {
    title: "Composition No II",
    year: "1913",
    originalSize: "88 x 115 cm",
    artist: "Piet Mondrian",
    artistLife: "1872-1944",
    sku: "AM-M-037",
    basePrice: 4512,
    currency: "AED",
    image: "/image/m/composition no II.jpg",
    options: [{ id: 'opt1', width: 88, height: 115, price: 4512, label: 'Original Size' }],
  },

  {
    title: "Tableau No I",
    year: "1913",
    originalSize: "96 x 64 cm",
    artist: "Piet Mondrian",
    artistLife: "1872-1944",
    sku: "AM-M-038",
    basePrice: 4166,
    currency: "AED",
    image: "/image/m/tableau no I.jpg",
    options: [{ id: 'opt1', width: 96, height: 64, price: 4166, label: 'Original Size' }],
  },

  {
    title: "Composition Red, Yellow and Blue",
    year: "1927",
    originalSize: "40 x 52 cm",
    artist: "Piet Mondrian",
    artistLife: "1872-1944",
    sku: "AM-M-039",
    basePrice: 1373,
    currency: "AED",
    image: "/image/m/composition red, yellow and blue.jpg",
    options: [{ id: 'opt1', width: 40, height: 52, price: 1373, label: 'Original Size' }],
  },

  {
    title: "Composition Of Red and White",
    year: "1938",
    originalSize: "100.3 x 99 cm",
    artist: "Piet Mondrian",
    artistLife: "1872-1944",
    sku: "AM-M-040",
    basePrice: 3482,
    currency: "AED",
    image: "/image/m/composition of red and white.jpg",
    options: [{ id: 'opt1', width: 100.3, height: 99, price: 3482, label: 'Original Size' }],
  },

  {
    title: "The Hunt",
    year: "1876",
    originalSize: "170 x 137 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-041",
    basePrice: 8500,
    currency: "AED",
    image: "/image/m/the hunt.jpg",
    options: [{ id: 'opt1', width: 170, height: 137, price: 8500, label: 'Original Size' }],
  },

  {
    title: "The Water Lily Pond",
    year: "1904",
    originalSize: "90 x 92 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-042",
    basePrice: 3278,
    currency: "AED",
    image: "/image/m/the water lily pond.jpg",
    options: [{ id: 'opt1', width: 90, height: 92, price: 3278, label: 'Original Size' }],
  },

  {
    title: "Water Lilies",
    year: "1905",
    originalSize: "89.5 x 100.3 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-043",
    basePrice: 3330,
    currency: "AED",
    image: "/image/m/water lilies.jpg",
    options: [{ id: 'opt1', width: 89.5, height: 100.3, price: 3330, label: 'Original Size' }],
  },

  {
    title: "Water Lilies",
    year: "1908",
    originalSize: "101 x 90 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-044",
    basePrice: 3330,
    currency: "AED",
    image: "/image/m/water lilies.jpg",
    options: [{ id: 'opt1', width: 101, height: 90, price: 3330, label: 'Original Size' }],
  },

  {
    title: "Water Lilies",
    year: "1907",
    originalSize: "92.1 x 81.2 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-045",
    basePrice: 3200,
    currency: "AED",
    image: "/image/m/water lilies.jpg",
    options: [{ id: 'opt1', width: 92.1, height: 81.2, price: 3200, label: 'Original Size' }],
  },

  {
    title: "Water Lilies",
    year: "1905",
    originalSize: "88.3 x 99.5 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-046",
    basePrice: 3250,
    currency: "AED",
    image: "/image/m/water lilies.jpg",
    options: [{ id: 'opt1', width: 88.3, height: 99.5, price: 3250, label: 'Original Size' }],
  },

  {
    title: "Waterloo Bridge Gray Day",
    year: "1903",
    originalSize: "65.1 x 100 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-047",
    basePrice: 3021,
    currency: "AED",
    image: "/image/m/waterloo bridge gray day.jpg",
    options: [{ id: 'opt1', width: 65.1, height: 100, price: 3021, label: 'Original Size' }],
  },

  {
    title: "Haystacks In The Sunlight Midday",
    year: "1890",
    originalSize: "66.6 x 100.6 cm",
    artist: "Claude Monet",
    artistLife: "1840-1926",
    sku: "AM-M-048",
    basePrice: 2857,
    currency: "AED",
    image: "/image/m/haystacks in the sunlight midday.jpg",
    options: [{ id: 'opt1', width: 66.6, height: 100.6, price: 2857, label: 'Original Size' }],
  },

  {
    title: "Woman In Red Bathrobe",
    year: "1912",
    originalSize: "81.2 x 54.5 cm",
    artist: "James Wilson Morrice",
    artistLife: "1865-1924",
    sku: "AM-M-049",
    basePrice: 3047,
    currency: "AED",
    image: "/image/m/woman in red bathrobe.jpg",
    options: [{ id: 'opt1', width: 81.2, height: 54.5, price: 3047, label: 'Original Size' }],
  },

  {
    title: "House In Santiago",
    year: "1915",
    originalSize: "54 x 64.8 cm",
    artist: "James Wilson Morrice",
    artistLife: "1865-1924",
    sku: "AM-M-050",
    basePrice: 2024,
    currency: "AED",
    image: "/image/m/house in santiago.jpg",
    options: [{ id: 'opt1', width: 54, height: 64.8, price: 2024, label: 'Original Size' }],
  },

  {
    title: "Sailing Boats",
    year: "Unknown",
    originalSize: "61 x 81.3 cm",
    artist: "James Wilson Morrice",
    artistLife: "1865-1924",
    sku: "AM-M-051",
    basePrice: 2302,
    currency: "AED",
    image: "/image/m/sailing boats.jpg",
    options: [{ id: 'opt1', width: 61, height: 81.3, price: 2302, label: 'Original Size' }],
  },

];

export default mArtworks;
