export const oArtworks = [
  {
    title: "A Cloudy Day, Bluebonnets Near San Antonio, Texas",
    year: "1918",
    originalSize: "63.8 x 76.5 cm",
    artist: "Julian Onderdonk",
    artistLife: "1882-1922",
    sku: "AM-O-001",
    basePrice: 3313,
    currency: "AED",
    image: "/image/o/A Cloudy Day, Bluebonnets Near San Antonio, Texas.jpg",
    options: [{ id: 'opt1', width: 63.8, height: 76.5, price: 3313, label: 'Original Size' }],
  },

  {
    title: "October Sunlight",
    year: "1911",
    originalSize: "22.8 x 30.5 cm",
    artist: "Julian Onderdonk",
    artistLife: "1882-1922",
    sku: "AM-O-002",
    basePrice: 1723,
    currency: "AED",
    image: "/image/o/October Sunlight.jpg",
    options: [{ id: 'opt1', width: 22.8, height: 30.5, price: 1723, label: 'Original Size' }],
  },

  {
    title: "Fall Landscape",
    year: "Unknown",
    originalSize: "23 x 30.5 cm",
    artist: "Julian Onderdonk",
    artistLife: "1882-1922",
    sku: "AM-O-003",
    basePrice: 1728,
    currency: "AED",
    image: "/image/o/Fall Landscape.jpg",
    options: [{ id: 'opt1', width: 23, height: 30.5, price: 1728, label: 'Original Size' }],
  },

  {
    title: "Female Martyr",
    year: "Unknown",
    originalSize: "74.3 x 56.8 cm",
    artist: "Jacob Van Oost The Elder",
    artistLife: "1601-1671",
    sku: "AM-O-004",
    basePrice: 4855,
    currency: "AED",
    image: "/image/o/Female Martyr.jpg",
    options: [{ id: 'opt1', width: 74.3, height: 56.8, price: 4855, label: 'Original Size' }],
  },

  {
    title: "Saint Anthony Raising Man From The Dead",
    year: "1640",
    originalSize: "176 x 104 cm",
    artist: "Jacob Van Oost The Elder",
    artistLife: "1601-1671",
    sku: "AM-O-005",
    basePrice: 8581,
    currency: "AED",
    image: "/image/o/Saint Anthony Raising Man From The Dead.jpg",
    options: [{ id: 'opt1', width: 176, height: 104, price: 8581, label: 'Original Size' }],
  },

  {
    title: "Winston Churchill",
    year: "1916",
    originalSize: "148 x 102.5 cm",
    artist: "Sir William Orpen",
    artistLife: "1878-1931",
    sku: "AM-O-006",
    basePrice: 6048,
    currency: "AED",
    image: "/image/o/Winston Churchill.jpg",
    options: [{ id: 'opt1', width: 148, height: 102.5, price: 6048, label: 'Original Size' }],
  },

  {
    title: "Lieutenant General Sir Arthur Currie",
    year: "1919",
    originalSize: "91.8 x 71.5 cm",
    artist: "Sir William Orpen",
    artistLife: "1878-1931",
    sku: "AM-O-007",
    basePrice: 4709,
    currency: "AED",
    image: "/image/o/Lieutenant General Sir Arthur Currie.jpg",
    options: [{ id: 'opt1', width: 91.8, height: 71.5, price: 4709, label: 'Original Size' }],
  },

  {
    title: "Italia and Germania",
    year: "1828",
    originalSize: "94.5 x 104.7 cm",
    artist: "Jonathan Friedrich Overbeck",
    artistLife: "1789-1869",
    sku: "AM-O-008",
    basePrice: 15030,
    currency: "AED",
    image: "/image/o/Italia and Germania.jpg",
    options: [{ id: 'opt1', width: 94.5, height: 104.7, price: 15030, label: 'Original Size' }],
  },

  {
    title: "The Marriage of the Virgin",
    year: "1839",
    originalSize: "89 x 71 cm",
    artist: "Jonathan Friedrich Overbeck",
    artistLife: "1789-1869",
    sku: "AM-O-009",
    basePrice: 25173,
    currency: "AED",
    image: "/image/o/The Marriage of the Virgin.jpg",
    options: [{ id: 'opt1', width: 89, height: 71, price: 25173, label: 'Original Size' }],
  },

  {
    title: "Vittoria Caldoni",
    year: "1821",
    originalSize: "89.5 x 65.8 cm",
    artist: "Jonathan Friedrich Overbeck",
    artistLife: "1789-1869",
    sku: "AM-O-010",
    basePrice: 13495,
    currency: "AED",
    image: "/image/o/Vittoria Caldoni.jpg",
    options: [{ id: 'opt1', width: 89.5, height: 65.8, price: 13495, label: 'Original Size' }],
  },

  {
    title: "The Raising of Lazarus",
    year: "1808",
    originalSize: "41 x 53 cm",
    artist: "Jonathan Friedrich Overbeck",
    artistLife: "1789-1869",
    sku: "AM-O-011",
    basePrice: 21726,
    currency: "AED",
    image: "/image/o/The Raising of Lazarus.jpg",
    options: [{ id: 'opt1', width: 41, height: 53, price: 21726, label: 'Original Size' }],
  },

];

export default oArtworks;
