export const pArtworks = [
  {
    title: "Dantes Dream From The Divine Comedy",
    year: "Unknown",
    originalSize: "68 x 61 cm",
    artist: "Sir Joseph Noel Paton",
    artistLife: "1821-1901",
    sku: "AM-P-001",
    basePrice: 8287,
    currency: "AED",
    image: "/image/P/Dantes Dream From The Divine Comedy.jpg",
    options: [{ id: 'opt1', width: 68, height: 61, price: 8287, label: 'Original Size' }],
  },

  {
    title: "Puck And Fairies From Mid-Summer's Night Dream",
    year: "1850",
    originalSize: "26.4 x 31.2 cm",
    artist: "Sir Joseph Noel Paton",
    artistLife: "1821-1901",
    sku: "AM-P-002",
    basePrice: 6469,
    currency: "AED",
    image: "/image/P/Puck and Fairies From Mid-Summer's Night Dream.jpg",
    options: [{ id: 'opt1', width: 26.4, height: 31.2, price: 6469, label: 'Original Size' }],
  },

  {
    title: "Monument Valley Riverbed",
    year: "Unknown",
    originalSize: "64.1 x 76.8 cm",
    artist: "Edgar Alwin Payne",
    artistLife: "1883-1947",
    sku: "AM-P-003",
    basePrice: 2638,
    currency: "AED",
    image: "/image/P/Monument Valley Riverbed.jpg",
    options: [{ id: 'opt1', width: 64.1, height: 76.8, price: 2638, label: 'Original Size' }],
  },

  {
    title: "Apples",
    year: "1917",
    originalSize: "41.5 x 58 cm",
    artist: "Kuzma Petrov Vodkin",
    artistLife: "1878-1939",
    sku: "AM-P-004",
    basePrice: 2493,
    currency: "AED",
    image: "/image/P/Apples.jpg",
    options: [{ id: 'opt1', width: 41.5, height: 58, price: 2493, label: 'Original Size' }],
  },

  {
    title: "Crouching Woman (Jacqueline)",
    year: "1954",
    originalSize: "146 x 114 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-005",
    basePrice: 4400,
    currency: "AED",
    image: "/image/P/Crouching Woman (Jacqueline).jpg",
    options: [{ id: 'opt1', width: 146, height: 114, price: 4400, label: 'Original Size' }],
  },

  {
    title: "Writing Woman",
    year: "1934",
    originalSize: "81 x 64.7 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-006",
    basePrice: 2724,
    currency: "AED",
    image: "/image/P/Writing WOman.jpg",
    options: [{ id: 'opt1', width: 81, height: 64.7, price: 2724, label: 'Original Size' }],
  },

  {
    title: "Nude, Green Leaves And Bust",
    year: "1932",
    originalSize: "162 x 130 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-007",
    basePrice: 5650,
    currency: "AED",
    image: "/image/P/Nude, Green Leaves and Bust.jpg",
    options: [{ id: 'opt1', width: 162, height: 130, price: 5650, label: 'Original Size' }],
  },

  {
    title: "Appointment",
    year: "1900",
    originalSize: "53 x 56 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-008",
    basePrice: 1898,
    currency: "AED",
    image: "/image/P/Appointment.jpg",
    options: [{ id: 'opt1', width: 53, height: 56, price: 1898, label: 'Original Size' }],
  },

  {
    title: "The Tragedy",
    year: "1903",
    originalSize: "86 x 56 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-009",
    basePrice: 3737,
    currency: "AED",
    image: "/image/P/The Tragedy.jpg",
    options: [{ id: 'opt1', width: 86, height: 56, price: 3737, label: 'Original Size' }],
  },

  {
    title: "The Old Guitarist",
    year: "1903",
    originalSize: "123 x 82.6 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-010",
    basePrice: 4809,
    currency: "AED",
    image: "/image/P/The Old Guitarist.jpg",
    options: [{ id: 'opt1', width: 123, height: 82.6, price: 4809, label: 'Original Size' }],
  },

  {
    title: "Dora Mar With Cat",
    year: "1941",
    originalSize: "128 x 95 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-011",
    basePrice: 4559,
    currency: "AED",
    image: "/image/P/Dora Mar With Cat.jpg",
    options: [{ id: 'opt1', width: 128, height: 95, price: 4559, label: 'Original Size' }],
  },

  {
    title: "A Girl Before A Mirror",
    year: "1932",
    originalSize: "162.3 x 130.2 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-012",
    basePrice: 6690,
    currency: "AED",
    image: "/image/P/A Girl Before A Mirror.jpg",
    options: [{ id: 'opt1', width: 162.3, height: 130.2, price: 6690, label: 'Original Size' }],
  },

  {
    title: "Women Of Algiers",
    year: "1955",
    originalSize: "114 x 146.4 cm",
    artist: "Pablo Picasso",
    artistLife: "1881-1973",
    sku: "AM-P-013",
    basePrice: 10499,
    currency: "AED",
    image: "/image/P/Women Of Algiers.jpg",
    options: [{ id: 'opt1', width: 114, height: 146.4, price: 10499, label: 'Original Size' }],
  },

  {
    title: "Quai Malaquais, Sunny Afternoon",
    year: "1903",
    originalSize: "65.3 x 81.5 cm",
    artist: "Camille Jacob Pissarro",
    artistLife: "1830-1903",
    sku: "AM-P-014",
    basePrice: 3274,
    currency: "AED",
    image: "/image/P/Quai Malaquais, Sunny Afternoon.jpg",
    options: [{ id: 'opt1', width: 65.3, height: 81.5, price: 3274, label: 'Original Size' }],
  },

  {
    title: "The Pont Royal And Pavillion De Flore",
    year: "1903",
    originalSize: "54 x 65 cm",
    artist: "Camille Jacob Pissarro",
    artistLife: "1830-1903",
    sku: "AM-P-015",
    basePrice: 2637,
    currency: "AED",
    image: "/image/P/The Pont Royal and Pavillion De Flore.jpg",
    options: [{ id: 'opt1', width: 54, height: 65, price: 2637, label: 'Original Size' }],
  },

  {
    title: "L'Avenue De L'Opera",
    year: "1898",
    originalSize: "65 x 82 cm",
    artist: "Camille Jacob Pissarro",
    artistLife: "1830-1903",
    sku: "AM-P-016",
    basePrice: 3321,
    currency: "AED",
    image: "/image/P/L'Avenue De L'Opera.jpg",
    options: [{ id: 'opt1', width: 65, height: 82, price: 3321, label: 'Original Size' }],
  },

  {
    title: "Boulevard Montemarte Afternoon In The Rain",
    year: "1897",
    originalSize: "61 x 75 cm",
    artist: "Camille Jacob Pissarro",
    artistLife: "1830-1903",
    sku: "AM-P-017",
    basePrice: 4993,
    currency: "AED",
    image: "/image/P/Boulevard Montemarte Afternoon In The Rain.jpg",
    options: [{ id: 'opt1', width: 61, height: 75, price: 4993, label: 'Original Size' }],
  },

  {
    title: "Brother And Sister",
    year: "1915",
    originalSize: "61.3 x 51 cm",
    artist: "Edward Henry Potthast",
    artistLife: "1857-1927",
    sku: "AM-P-018",
    basePrice: 3445,
    currency: "AED",
    image: "/image/P/Brother and Sister.jpg",
    options: [{ id: 'opt1', width: 61.3, height: 51, price: 3445, label: 'Original Size' }],
  },

  {
    title: "A Sailing Party",
    year: "1924",
    originalSize: "76.7 x 101.8 cm",
    artist: "Edward Henry Potthast",
    artistLife: "1857-1927",
    sku: "AM-P-019",
    basePrice: 3770,
    currency: "AED",
    image: "/image/P/A Sailing Party.jpg",
    options: [{ id: 'opt1', width: 76.7, height: 101.8, price: 3770, label: 'Original Size' }],
  },

  {
    title: "Holland Peasant With Cow",
    year: "1890",
    originalSize: "65 x 81 cm",
    artist: "Edward Henry Potthast",
    artistLife: "1857-1927",
    sku: "AM-P-020",
    basePrice: 2535,
    currency: "AED",
    image: "/image/P/Holland Peasant With Cow.jpg",
    options: [{ id: 'opt1', width: 65, height: 81, price: 2535, label: 'Original Size' }],
  },

  {
    title: "Dutch Interior",
    year: "1890",
    originalSize: "50 x 64.8 cm",
    artist: "Edward Henry Potthast",
    artistLife: "1857-1927",
    sku: "AM-P-021",
    basePrice: 3364,
    currency: "AED",
    image: "/image/P/Dutch Interior.jpg",
    options: [{ id: 'opt1', width: 50, height: 64.8, price: 3364, label: 'Original Size' }],
  },

  {
    title: "Vanity",
    year: "1650",
    originalSize: "93.5 x 65 cm",
    artist: "Mattia Preti",
    artistLife: "1613-1699",
    sku: "AM-P-022",
    basePrice: 11996,
    currency: "AED",
    image: "/image/P/Vanity.jpg",
    options: [{ id: 'opt1', width: 93.5, height: 65, price: 11996, label: 'Original Size' }],
  },

  {
    title: "The Queen Of Sheba Before Solomon",
    year: "Unknown",
    originalSize: "230 x 309 cm",
    artist: "Mattia Preti",
    artistLife: "1613-1699",
    sku: "AM-P-023",
    basePrice: 32035,
    currency: "AED",
    image: "/image/P/The Queen Of Sheba Before Solomon.jpg",
    options: [{ id: 'opt1', width: 230, height: 309, price: 32035, label: 'Original Size' }],
  },

  {
    title: "John The Baptist Preaching",
    year: "1667",
    originalSize: "217.2 x 170.2 cm",
    artist: "Mattia Preti",
    artistLife: "1613-1699",
    sku: "AM-P-024",
    basePrice: 20559,
    currency: "AED",
    image: "/image/P/John The Baptist Preaching.jpg",
    options: [{ id: 'opt1', width: 217.2, height: 170.2, price: 20559, label: 'Original Size' }],
  },

  {
    title: "St Paul The Hermit",
    year: "1660",
    originalSize: "125 x 101 cm",
    artist: "Mattia Preti",
    artistLife: "1613-1699",
    sku: "AM-P-025",
    basePrice: 13643,
    currency: "AED",
    image: "/image/P/St Paul The Hermit.jpg",
    options: [{ id: 'opt1', width: 125, height: 101, price: 13643, label: 'Original Size' }],
  },

  {
    title: "Interior Of St George's Chapel",
    year: "1838",
    originalSize: "91 x 64 cm",
    artist: "James Baker Pyne",
    artistLife: "1800-1870",
    sku: "AM-P-026",
    basePrice: 12091,
    currency: "AED",
    image: "/image/P/Interior Of St George's Chapel.jpg",
    options: [{ id: 'opt1', width: 91, height: 64, price: 12091, label: 'Original Size' }],
  },

  {
    title: "The Queen's Private Sitting Room Windsor Castle",
    year: "1838",
    originalSize: "63 x 91 cm",
    artist: "James Baker Pyne",
    artistLife: "1800-1870",
    sku: "AM-P-027",
    basePrice: 10737,
    currency: "AED",
    image: "/image/P/The Queen's Private Sitting Room Windsor Castle.jpg",
    options: [{ id: 'opt1', width: 63, height: 91, price: 10737, label: 'Original Size' }],
  },

  {
    title: "The Library Windsor Castle",
    year: "1838",
    originalSize: "68 x 91 cm",
    artist: "James Baker Pyne",
    artistLife: "1800-1870",
    sku: "AM-P-028",
    basePrice: 10000,
    currency: "AED",
    image: "/image/P/The Library Windsor Castle.jpg",
    options: [{ id: 'opt1', width: 68, height: 91, price: 10000, label: 'Original Size' }],
  },

];

export default pArtworks;
