export const tArtworks = [
  {
    title: "Three Sisters A Study In June Sunlight",
    year: "1890",
    originalSize: "89.2 x 102 cm",
    artist: "Edward Charles Tarbell",
    artistLife: "1862-1938",
    sku: "AM-T-001",
    basePrice: 5384,
    currency: "AED",
    image: "/image/t/Three Sisters A Study In June Sunlight.jpg",
    options: [{ id: 'opt1', width: 89.2, height: 102, price: 5384, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Lady",
    year: "Unknown",
    originalSize: "86.3 x 61 cm",
    artist: "Edward Charles Tarbell",
    artistLife: "1862-1938",
    sku: "AM-T-002",
    basePrice: 3493,
    currency: "AED",
    image: "/image/t/Portrait Of A Lady.jpg",
    options: [{ id: 'opt1', width: 86.3, height: 61, price: 3493, label: 'Original Size' }],
  },

  {
    title: "The Blue Veil",
    year: "1898",
    originalSize: "73.7 x 61 cm",
    artist: "Edward Charles Tarbell",
    artistLife: "1862-1938",
    sku: "AM-T-003",
    basePrice: 3079,
    currency: "AED",
    image: "/image/t/The Blue Veil.jpg",
    options: [{ id: 'opt1', width: 73.7, height: 61, price: 3079, label: 'Original Size' }],
  },

  {
    title: "Mother And Child In A Boat",
    year: "1892",
    originalSize: "76.5 x 89 cm",
    artist: "Edward Charles Tarbell",
    artistLife: "1862-1938",
    sku: "AM-T-004",
    basePrice: 3497,
    currency: "AED",
    image: "/image/t/Mother And Child In A Boat.jpg",
    options: [{ id: 'opt1', width: 76.5, height: 89, price: 3497, label: 'Original Size' }],
  },

  {
    title: "Reverie (Kathering Finn)",
    year: "1913",
    originalSize: "127.3 x 86.7 cm",
    artist: "Edward Charles Tarbell",
    artistLife: "1862-1938",
    sku: "AM-T-005",
    basePrice: 4522,
    currency: "AED",
    image: "/image/t/Reverie (Kathering Finn).jpg",
    options: [{ id: 'opt1', width: 127.3, height: 86.7, price: 4522, label: 'Original Size' }],
  },

  {
    title: "Woman Drinking With Sleeping Soldier",
    year: "1660",
    originalSize: "46 x 40 cm",
    artist: "Gerard Ter Boch",
    artistLife: "1617-1681",
    sku: "AM-T-006",
    basePrice: 5671,
    currency: "AED",
    image: "/image/t/Woman Drinking With Sleeping Soldier.jpg",
    options: [{ id: 'opt1', width: 46, height: 40, price: 5671, label: 'Original Size' }],
  },

  {
    title: "Woman Peeling Apples",
    year: "1660",
    originalSize: "36.3 x 30.7 cm",
    artist: "Gerard Ter Boch",
    artistLife: "1617-1681",
    sku: "AM-T-007",
    basePrice: 6667,
    currency: "AED",
    image: "/image/t/Woman Peeling Apples.jpg",
    options: [{ id: 'opt1', width: 36.3, height: 30.7, price: 6667, label: 'Original Size' }],
  },

  {
    title: "Man Offering A Woman Cpins",
    year: "1662",
    originalSize: "68 x 65 cm",
    artist: "Gerard Ter Boch",
    artistLife: "1617-1681",
    sku: "AM-T-008",
    basePrice: 7680,
    currency: "AED",
    image: "/image/t/Man Offering A Woman Cpins.jpg",
    options: [{ id: 'opt1', width: 68, height: 65, price: 7680, label: 'Original Size' }],
  },

  {
    title: "The Suitor's Visit",
    year: "1658",
    originalSize: "80 x 75 cm",
    artist: "Gerard Ter Boch",
    artistLife: "1617-1681",
    sku: "AM-T-009",
    basePrice: 11913,
    currency: "AED",
    image: "/image/t/The Suitor's Visit.jpg",
    options: [{ id: 'opt1', width: 80, height: 75, price: 11913, label: 'Original Size' }],
  },

  {
    title: "A Lady At Her Toilet",
    year: "1660",
    originalSize: "76.2 x 58.4 cm",
    artist: "Gerard Ter Boch",
    artistLife: "1617-1681",
    sku: "AM-T-010",
    basePrice: 8976,
    currency: "AED",
    image: "/image/t/A Lady At Her Toilet.jpg",
    options: [{ id: 'opt1', width: 76.2, height: 58.4, price: 8976, label: 'Original Size' }],
  },

  {
    title: "Young Woman In A Boat",
    year: "1870",
    originalSize: "50.1 x 64.7 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-011",
    basePrice: 1870,
    currency: "AED",
    image: "/image/t/Young Woman In A Boat.jpg",
    options: [{ id: 'opt1', width: 50.1, height: 64.7, price: 1870, label: 'Original Size' }],
  },

  {
    title: "October",
    year: "1877",
    originalSize: "216 x 108.7 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-012",
    basePrice: 19962,
    currency: "AED",
    image: "/image/t/October.jpg",
    options: [{ id: 'opt1', width: 216, height: 108.7, price: 19962, label: 'Original Size' }],
  },

  {
    title: "The Letter",
    year: "1876",
    originalSize: "71.4 x 107.1 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-013",
    basePrice: 9315,
    currency: "AED",
    image: "/image/t/The Letter.jpg",
    options: [{ id: 'opt1', width: 71.4, height: 107.1, price: 9315, label: 'Original Size' }],
  },

  {
    title: "The Gallery Of H M S Calcutta",
    year: "1877",
    originalSize: "68.6 x 91.8 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-014",
    basePrice: 8611,
    currency: "AED",
    image: "/image/t/The Gallery Of H M S Calcutta.jpg",
    options: [{ id: 'opt1', width: 68.6, height: 91.8, price: 8611, label: 'Original Size' }],
  },

  {
    title: "The Thames",
    year: "1876",
    originalSize: "72.5 x 118 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-015",
    basePrice: 9401,
    currency: "AED",
    image: "/image/t/The Thames.jpg",
    options: [{ id: 'opt1', width: 72.5, height: 118, price: 9401, label: 'Original Size' }],
  },

  {
    title: "The Convalescent",
    year: "1876",
    originalSize: "61 x 78 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-016",
    basePrice: 9152,
    currency: "AED",
    image: "/image/t/The Convalescent.jpg",
    options: [{ id: 'opt1', width: 61, height: 78, price: 9152, label: 'Original Size' }],
  },

  {
    title: "The Portrait (Miss Lloyd)",
    year: "1876",
    originalSize: "91.4 x 50.8 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-017",
    basePrice: 6667,
    currency: "AED",
    image: "/image/t/The Portrait (Miss Lloyd).jpg",
    options: [{ id: 'opt1', width: 91.4, height: 50.8, price: 6667, label: 'Original Size' }],
  },

  {
    title: "The Political Lady",
    year: "1883",
    originalSize: "142.2 x 101.6 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-018",
    basePrice: 15025,
    currency: "AED",
    image: "/image/t/The Political Lady.jpg",
    options: [{ id: 'opt1', width: 142.2, height: 101.6, price: 15025, label: 'Original Size' }],
  },

  {
    title: "The Shop Girl ( The Millner's Shop)",
    year: "1883",
    originalSize: "146 x 101.6 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-019",
    basePrice: 15025,
    currency: "AED",
    image: "/image/t/The Shop Girl ( The Millner's Shop).jpg",
    options: [{ id: 'opt1', width: 146, height: 101.6, price: 15025, label: 'Original Size' }],
  },

  {
    title: "On The Thames",
    year: "1882",
    originalSize: "81 x 56 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-020",
    basePrice: 10711,
    currency: "AED",
    image: "/image/t/On The Thames.jpg",
    options: [{ id: 'opt1', width: 81, height: 56, price: 10711, label: 'Original Size' }],
  },

  {
    title: "Richmond Bridge",
    year: "1878",
    originalSize: "37 x 23.5 cm",
    artist: "James Jaques Joseph Tissot",
    artistLife: "1836-1902",
    sku: "AM-T-021",
    basePrice: 4293,
    currency: "AED",
    image: "/image/t/Richmond Bridge.jpg",
    options: [{ id: 'opt1', width: 37, height: 23.5, price: 4293, label: 'Original Size' }],
  },

  {
    title: "At The Moulin Rouge, The Dance",
    year: "1890",
    originalSize: "150 x 115.5 cm",
    artist: "Henri De Toulouse-Lautrec",
    artistLife: "1864-1901",
    sku: "AM-T-022",
    basePrice: 6976,
    currency: "AED",
    image: "/image/t/At The Moulin Rouge, The Dance.jpg",
    options: [{ id: 'opt1', width: 150, height: 115.5, price: 6976, label: 'Original Size' }],
  },

  {
    title: "Marcelle Lender Dancing The Bolero In Chilperic",
    year: "1895",
    originalSize: "145 x 149 cm",
    artist: "Henri De Toulouse-Lautrec",
    artistLife: "1864-1901",
    sku: "AM-T-023",
    basePrice: 5842,
    currency: "AED",
    image: "/image/t/Marcelle Lender Dancing The Bolero In Chilperic.jpg",
    options: [{ id: 'opt1', width: 145, height: 149, price: 5842, label: 'Original Size' }],
  },

  {
    title: "The Bathers",
    year: "1889",
    originalSize: "116.8 x 86.3 cm",
    artist: "Henry Scott Tuke",
    artistLife: "1858-1929",
    sku: "AM-T-024",
    basePrice: 6010,
    currency: "AED",
    image: "/image/t/The Bathers.jpg",
    options: [{ id: 'opt1', width: 116.8, height: 86.3, price: 6010, label: 'Original Size' }],
  },

  {
    title: "Boys Bathing",
    year: "1908",
    originalSize: "61 x 45.7 cm",
    artist: "Henry Scott Tuke",
    artistLife: "1858-1929",
    sku: "AM-T-025",
    basePrice: 4473,
    currency: "AED",
    image: "/image/t/Boys Bathing.jpg",
    options: [{ id: 'opt1', width: 61, height: 45.7, price: 4473, label: 'Original Size' }],
  },

  {
    title: "Drinking",
    year: "1881",
    originalSize: "23 x 15.2 cm",
    artist: "Henry Scott Tuke",
    artistLife: "1858-1929",
    sku: "AM-T-026",
    basePrice: 2236,
    currency: "AED",
    image: "/image/t/Drinking.jpg",
    options: [{ id: 'opt1', width: 23, height: 15.2, price: 2236, label: 'Original Size' }],
  },

  {
    title: "Bluebells",
    year: "1907",
    originalSize: "45.7 x 30.5 cm",
    artist: "Henry Scott Tuke",
    artistLife: "1858-1929",
    sku: "AM-T-027",
    basePrice: 3820,
    currency: "AED",
    image: "/image/t/Bluebells.jpg",
    options: [{ id: 'opt1', width: 45.7, height: 30.5, price: 3820, label: 'Original Size' }],
  },

];

export default tArtworks;
