export const vArtworks = [
  {
    title: "Still Life With Peaches And Grapes",
    year: "1779",
    originalSize: "46 x 55 cm",
    artist: "Anne Vallayer-Coster",
    artistLife: "1744-1818",
    sku: "AM-V-001",
    basePrice: 9131,
    currency: "AED",
    image: "/image/v/Still Life with Peaches and Grapes.jpg",
    options: [{ id: 'opt1', width: 46, height: 55, price: 9131, label: 'Original Size' }],
  },

  {
    title: "Still Life With Ham",
    year: "1767",
    originalSize: "46 x 55 cm",
    artist: "Anne Vallayer-Coster",
    artistLife: "1744-1818",
    sku: "AM-V-002",
    basePrice: 4443,
    currency: "AED",
    image: "/image/v/Still Life with Ham.jpg",
    options: [{ id: 'opt1', width: 46, height: 55, price: 4443, label: 'Original Size' }],
  },

  {
    title: "Still Life With Peaches And Silver Mugs",
    year: "1797",
    originalSize: "36 x 47.5 cm",
    artist: "Anne Vallayer-Coster",
    artistLife: "1744-1818",
    sku: "AM-V-003",
    basePrice: 6787,
    currency: "AED",
    image: "/image/v/Still Life with Peaches and Silver Mugs.jpg",
    options: [{ id: 'opt1', width: 36, height: 47.5, price: 6787, label: 'Original Size' }],
  },

  {
    title: "Still Life With Bulbous Bottle",
    year: "1770",
    originalSize: "27.5 x 32.5 cm",
    artist: "Anne Vallayer-Coster",
    artistLife: "1744-1818",
    sku: "AM-V-004",
    basePrice: 2751,
    currency: "AED",
    image: "/image/v/Still Life with Bulbous Bottle.jpg",
    options: [{ id: 'opt1', width: 27.5, height: 32.5, price: 2751, label: 'Original Size' }],
  },

  {
    title: "Still Life With Mackrell",
    year: "1787",
    originalSize: "49.5 x 61 cm",
    artist: "Anne Vallayer-Coster",
    artistLife: "1744-1818",
    sku: "AM-V-005",
    basePrice: 13282,
    currency: "AED",
    image: "/image/v/Still Life with Mackrell.jpg",
    options: [{ id: 'opt1', width: 49.5, height: 61, price: 13282, label: 'Original Size' }],
  },

  {
    title: "King Philip IV Of Spain",
    year: "1644",
    originalSize: "129.8 x 99.3 cm",
    artist: "Diego Rodriguez De Silva Velazquez",
    artistLife: "1599-1660",
    sku: "AM-V-006",
    basePrice: 10925,
    currency: "AED",
    image: "/image/v/King Philip IV Of Spain.jpg",
    options: [{ id: 'opt1', width: 129.8, height: 99.3, price: 10925, label: 'Original Size' }],
  },

  {
    title: "The Water Seller Of Seville",
    year: "1620",
    originalSize: "106 x 82 cm",
    artist: "Diego Rodriguez De Silva Velazquez",
    artistLife: "1599-1660",
    sku: "AM-V-007",
    basePrice: 11084,
    currency: "AED",
    image: "/image/v/The Water seller of Seville.jpg",
    options: [{ id: 'opt1', width: 106, height: 82, price: 11084, label: 'Original Size' }],
  },

  {
    title: "An Old Woman Cooking Eggs",
    year: "1618",
    originalSize: "100.5 x 119.5 cm",
    artist: "Diego Rodriguez De Silva Velazquez",
    artistLife: "1599-1660",
    sku: "AM-V-008",
    basePrice: 17172,
    currency: "AED",
    image: "/image/v/An Old Woman Cooking Eggs.jpg",
    options: [{ id: 'opt1', width: 100.5, height: 119.5, price: 17172, label: 'Original Size' }],
  },

  {
    title: "Villa Medici In Rome (Pavillion Of Ariadne)",
    year: "1630",
    originalSize: "48.5 x 43 cm",
    artist: "Diego Rodriguez De Silva Velazquez",
    artistLife: "1599-1660",
    sku: "AM-V-009",
    basePrice: 3241,
    currency: "AED",
    image: "/image/v/Villa Medici In Rome (Pavillion of Ariadne).jpg",
    options: [{ id: 'opt1', width: 48.5, height: 43, price: 3241, label: 'Original Size' }],
  },

  {
    title: "Villa Medici In Rome (Facade Of Grotto Logia)",
    year: "1630",
    originalSize: "44 x 38 cm",
    artist: "Diego Rodriguez De Silva Velazquez",
    artistLife: "1599-1660",
    sku: "AM-V-010",
    basePrice: 2970,
    currency: "AED",
    image: "/image/v/Villa Medici In Rome (Facade of Grotto Logia).jpg",
    options: [{ id: 'opt1', width: 44, height: 38, price: 2970, label: 'Original Size' }],
  },

  {
    title: "The Girl With The Pearl Earring",
    year: "1665",
    originalSize: "46.5 x 40 cm",
    artist: "Johannes Vermeer Van Delft",
    artistLife: "1632-1675",
    sku: "AM-V-011",
    basePrice: 3039,
    currency: "AED",
    image: "/image/v/The Girl with the Pearl Earring.jpg",
    options: [{ id: 'opt1', width: 46.5, height: 40, price: 3039, label: 'Original Size' }],
  },

  {
    title: "The Milkmaid The Kitchen Maid",
    year: "1658",
    originalSize: "45.5 x 41 cm",
    artist: "Johannes Vermeer Van Delft",
    artistLife: "1632-1675",
    sku: "AM-V-012",
    basePrice: 8216,
    currency: "AED",
    image: "/image/v/The Milkmaid the Kitchen Maid.jpg",
    options: [{ id: 'opt1', width: 45.5, height: 41, price: 8216, label: 'Original Size' }],
  },

  {
    title: "Mistress And Maid",
    year: "1666",
    originalSize: "90.2 x 78.7 cm",
    artist: "Johannes Vermeer Van Delft",
    artistLife: "1632-1675",
    sku: "AM-V-013",
    basePrice: 10058,
    currency: "AED",
    image: "/image/v/Mistress And Maid.jpg",
    options: [{ id: 'opt1', width: 90.2, height: 78.7, price: 10058, label: 'Original Size' }],
  },

  {
    title: "Girl Reading A Letter At An Open Window",
    year: "1657",
    originalSize: "83 x 64.5 cm",
    artist: "Johannes Vermeer Van Delft",
    artistLife: "1632-1675",
    sku: "AM-V-014",
    basePrice: 10346,
    currency: "AED",
    image: "/image/v/Girl Reading a Letter at An Open Window.jpg",
    options: [{ id: 'opt1', width: 83, height: 64.5, price: 10346, label: 'Original Size' }],
  },

  {
    title: "Pope Julius, I Ordering Bramante, Michelangelo And Raphael To Construct The Vatican And St Peter's",
    year: "1827",
    originalSize: "88 x 101 cm",
    artist: "Horace Vernet",
    artistLife: "1789-1863",
    sku: "AM-V-015",
    basePrice: 21910,
    currency: "AED",
    image: "/image/v/Pope Julius, I Ordering Bramante, Michelangelo and Raphael to Construct the Vatican and St Peter's.jpg",
    options: [{ id: 'opt1', width: 88, height: 101, price: 21910, label: 'Original Size' }],
  },

  {
    title: "The Arab Tale Teller",
    year: "1833",
    originalSize: "99 x 136.5 cm",
    artist: "Horace Vernet",
    artistLife: "1789-1863",
    sku: "AM-V-016",
    basePrice: 26266,
    currency: "AED",
    image: "/image/v/The Arab Tale Teller.jpg",
    options: [{ id: 'opt1', width: 99, height: 136.5, price: 26266, label: 'Original Size' }],
  },

  {
    title: "Hunting In The Pontine Marshes",
    year: "1833",
    originalSize: "100 x 137 cm",
    artist: "Horace Vernet",
    artistLife: "1789-1863",
    sku: "AM-V-017",
    basePrice: 10317,
    currency: "AED",
    image: "/image/v/Hunting In the Pontine Marshes.jpg",
    options: [{ id: 'opt1', width: 100, height: 137, price: 10317, label: 'Original Size' }],
  },

  {
    title: "Departure For The Hunt In The Pontine Marshes",
    year: "1833",
    originalSize: "100 x 150.7 cm",
    artist: "Horace Vernet",
    artistLife: "1789-1863",
    sku: "AM-V-018",
    basePrice: 8272,
    currency: "AED",
    image: "/image/v/Departure For the Hunt in The Pontine Marshes.jpg",
    options: [{ id: 'opt1', width: 100, height: 150.7, price: 8272, label: 'Original Size' }],
  },

  {
    title: "Allegory Of Wisdom And Strength",
    year: "1580",
    originalSize: "214.6 x 167 cm",
    artist: "Paolo Cagliari Veronese",
    artistLife: "1528-1588",
    sku: "AM-V-019",
    basePrice: 36168,
    currency: "AED",
    image: "/image/v/Allegory Of Wisdom and Strength.jpg",
    options: [{ id: 'opt1', width: 214.6, height: 167, price: 36168, label: 'Original Size' }],
  },

  {
    title: "Mars And Venus United By Love",
    year: "1570",
    originalSize: "205.7 x 161 cm",
    artist: "Paolo Cagliari Veronese",
    artistLife: "1528-1588",
    sku: "AM-V-020",
    basePrice: 36142,
    currency: "AED",
    image: "/image/v/Mars And Venus United by Love.jpg",
    options: [{ id: 'opt1', width: 205.7, height: 161, price: 36142, label: 'Original Size' }],
  },

  {
    title: "Moses Saved From The Waters",
    year: "1580",
    originalSize: "57 x 43 cm",
    artist: "Paolo Cagliari Veronese",
    artistLife: "1528-1588",
    sku: "AM-V-021",
    basePrice: 15903,
    currency: "AED",
    image: "/image/v/Moses Saved from The Waters.jpg",
    options: [{ id: 'opt1', width: 57, height: 43, price: 15903, label: 'Original Size' }],
  },

  {
    title: "Respect",
    year: "1575",
    originalSize: "188 x 194.3 cm",
    artist: "Paolo Cagliari Veronese",
    artistLife: "1528-1588",
    sku: "AM-V-022",
    basePrice: 20966,
    currency: "AED",
    image: "/image/v/Respect.jpg",
    options: [{ id: 'opt1', width: 188, height: 194.3, price: 20966, label: 'Original Size' }],
  },

  {
    title: "The Family Of Darius Before Alexander",
    year: "1565",
    originalSize: "236.2 x 475 cm",
    artist: "Paolo Cagliari Veronese",
    artistLife: "1528-1588",
    sku: "AM-V-023",
    basePrice: 103100,
    currency: "AED",
    image: "/image/v/The Family of Darius Before Alexander.jpg",
    options: [{ id: 'opt1', width: 236.2, height: 475, price: 103100, label: 'Original Size' }],
  },

  {
    title: "The Marvellous Sauce",
    year: "1890",
    originalSize: "64 x 81 cm",
    artist: "Jehan Georges Vibert",
    artistLife: "1840-1902",
    sku: "AM-V-024",
    basePrice: 8202,
    currency: "AED",
    image: "/image/v/The Marvellous Sauce.jpg",
    options: [{ id: 'opt1', width: 64, height: 81, price: 8202, label: 'Original Size' }],
  },

  {
    title: "La Sieste",
    year: "Unknown",
    originalSize: "26 x 36 cm",
    artist: "Jehan Georges Vibert",
    artistLife: "1840-1902",
    sku: "AM-V-025",
    basePrice: 6473,
    currency: "AED",
    image: "/image/v/La Sieste.jpg",
    options: [{ id: 'opt1', width: 26, height: 36, price: 6473, label: 'Original Size' }],
  },

  {
    title: "The Church In Danger",
    year: "Unknown",
    originalSize: "73.7 x 58.4 cm",
    artist: "Jehan Georges Vibert",
    artistLife: "1840-1902",
    sku: "AM-V-026",
    basePrice: 13758,
    currency: "AED",
    image: "/image/v/The Church in Danger.jpg",
    options: [{ id: 'opt1', width: 73.7, height: 58.4, price: 13758, label: 'Original Size' }],
  },

  {
    title: "The View",
    year: "Unknown",
    originalSize: "36 x 27.7 cm",
    artist: "Jehan Georges Vibert",
    artistLife: "1840-1902",
    sku: "AM-V-027",
    basePrice: 5353,
    currency: "AED",
    image: "/image/v/The View.jpg",
    options: [{ id: 'opt1', width: 36, height: 27.7, price: 5353, label: 'Original Size' }],
  },

  {
    title: "The Convent Choir",
    year: "1865",
    originalSize: "37.5 x 46.4 cm",
    artist: "Jehan Georges Vibert",
    artistLife: "1840-1902",
    sku: "AM-V-028",
    basePrice: 11382,
    currency: "AED",
    image: "/image/v/The Convent Choir.jpg",
    options: [{ id: 'opt1', width: 37.5, height: 46.4, price: 11382, label: 'Original Size' }],
  },

  {
    title: "Tea For The Bishop",
    year: "Unknown",
    originalSize: "61 x 45.7 cm",
    artist: "Jehan Georges Vibert",
    artistLife: "1840-1902",
    sku: "AM-V-029",
    basePrice: 12464,
    currency: "AED",
    image: "/image/v/Tea For the Bishop.jpg",
    options: [{ id: 'opt1', width: 61, height: 45.7, price: 12464, label: 'Original Size' }],
  },

  {
    title: "Eruption In Vesuvius",
    year: "1771",
    originalSize: "71 x 124 cm",
    artist: "Pierre Jacques Voliare",
    artistLife: "1729-1802",
    sku: "AM-V-030",
    basePrice: 17239,
    currency: "AED",
    image: "/image/v/Eruption In Vesuvius.jpg",
    options: [{ id: 'opt1', width: 71, height: 124, price: 17239, label: 'Original Size' }],
  },

  {
    title: "The Eruption Of Vesuvius",
    year: "Unknown",
    originalSize: "51 x 115 cm",
    artist: "Pierre Jacques Voliare",
    artistLife: "1729-1802",
    sku: "AM-V-031",
    basePrice: 7365,
    currency: "AED",
    image: "/image/v/The Eruption of Vesuvius.jpg",
    options: [{ id: 'opt1', width: 51, height: 115, price: 7365, label: 'Original Size' }],
  },

  {
    title: "The Eruption Of Vesuvius 2",
    year: "Unknown",
    originalSize: "51 x 34 cm",
    artist: "Pierre Jacques Voliare",
    artistLife: "1729-1802",
    sku: "AM-V-032",
    basePrice: 4271,
    currency: "AED",
    image: "/image/v/The Eruption of Vesuvius 2.jpg",
    options: [{ id: 'opt1', width: 51, height: 34, price: 4271, label: 'Original Size' }],
  },

  {
    title: "Apple Bloom",
    year: "1903",
    originalSize: "76.8 x 92 cm",
    artist: "Robert Vennoh",
    artistLife: "1858-1930",
    sku: "AM-V-033",
    basePrice: 3004,
    currency: "AED",
    image: "/image/v/Apple Bloom.jpg",
    options: [{ id: 'opt1', width: 76.8, height: 92, price: 3004, label: 'Original Size' }],
  },

  {
    title: "The Flanders Field Where Soldiers Sleep And Poppies Grow",
    year: "1890",
    originalSize: "61 x 110 cm",
    artist: "Robert Vennoh",
    artistLife: "1858-1930",
    sku: "AM-V-034",
    basePrice: 3357,
    currency: "AED",
    image: "/image/v/The Flanders Field Where Soldiers Sleep And Poppies Grow.jpg",
    options: [{ id: 'opt1', width: 61, height: 110, price: 3357, label: 'Original Size' }],
  },

  {
    title: "The Bridge At Grez",
    year: "1907",
    originalSize: "61 x 86 cm",
    artist: "Robert Vennoh",
    artistLife: "1858-1930",
    sku: "AM-V-035",
    basePrice: 2853,
    currency: "AED",
    image: "/image/v/The Bridge at Grez.jpg",
    options: [{ id: 'opt1', width: 61, height: 86, price: 2853, label: 'Original Size' }],
  },

  {
    title: "Jardin De Paysanne",
    year: "1890",
    originalSize: "65.7 x 50.2 cm",
    artist: "Robert Vennoh",
    artistLife: "1858-1930",
    sku: "AM-V-036",
    basePrice: 2801,
    currency: "AED",
    image: "/image/v/Jardin De Paysanne.jpg",
    options: [{ id: 'opt1', width: 65.7, height: 50.2, price: 2801, label: 'Original Size' }],
  },

  {
    title: "Poppies In France",
    year: "1888",
    originalSize: "30.8 x 51 cm",
    artist: "Robert Vennoh",
    artistLife: "1858-1930",
    sku: "AM-V-037",
    basePrice: 2766,
    currency: "AED",
    image: "/image/v/Poppies In France.jpg",
    options: [{ id: 'opt1', width: 30.8, height: 51, price: 2766, label: 'Original Size' }],
  },

  {
    title: "Sleeping Venus",
    year: "1630",
    originalSize: "66 x 56 cm",
    artist: "Simon Vouet",
    artistLife: "1590-1649",
    sku: "AM-V-038",
    basePrice: 6197,
    currency: "AED",
    image: "/image/v/Sleeping Venus.jpg",
    options: [{ id: 'opt1', width: 66, height: 56, price: 6197, label: 'Original Size' }],
  },

  {
    title: "Wealth",
    year: "1635",
    originalSize: "170 x 124 cm",
    artist: "Simon Vouet",
    artistLife: "1590-1649",
    sku: "AM-V-039",
    basePrice: 12494,
    currency: "AED",
    image: "/image/v/Wealth.jpg",
    options: [{ id: 'opt1', width: 170, height: 124, price: 12494, label: 'Original Size' }],
  },

  {
    title: "Model For Alterpiece In St Peter's",
    year: "1625",
    originalSize: "40.6 x 61.6 cm",
    artist: "Simon Vouet",
    artistLife: "1590-1649",
    sku: "AM-V-040",
    basePrice: 5445,
    currency: "AED",
    image: "/image/v/Model For Alterpiece in St Peter's.jpg",
    options: [{ id: 'opt1', width: 40.6, height: 61.6, price: 5445, label: 'Original Size' }],
  },

  {
    title: "Model For Alterpiece In St Peter's 1",
    year: "1625",
    originalSize: "40.6 x 61.6 cm",
    artist: "Simon Vouet",
    artistLife: "1590-1649",
    sku: "AM-V-041",
    basePrice: 5445,
    currency: "AED",
    image: "/image/v/Model For Alterpiece in St Peter's 1.jpg",
    options: [{ id: 'opt1', width: 40.6, height: 61.6, price: 5445, label: 'Original Size' }],
  },

  {
    title: "The Voiles De Genes' Boudoir",
    year: "1931",
    originalSize: "88 x 79.5 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-042",
    basePrice: 3787,
    currency: "AED",
    image: "/image/v/The Voiles De Genes' Boudoir.jpg",
    options: [{ id: 'opt1', width: 88, height: 79.5, price: 3787, label: 'Original Size' }],
  },

  {
    title: "In A Room",
    year: "1899",
    originalSize: "52 x 79 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-043",
    basePrice: 2697,
    currency: "AED",
    image: "/image/v/In A Room.jpg",
    options: [{ id: 'opt1', width: 52, height: 79, price: 2697, label: 'Original Size' }],
  },

  {
    title: "The Guinguette",
    year: "1898",
    originalSize: "33 x 27 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-044",
    basePrice: 1038,
    currency: "AED",
    image: "/image/v/The Guinguette.jpg",
    options: [{ id: 'opt1', width: 33, height: 27, price: 1038, label: 'Original Size' }],
  },

  {
    title: "Woman In A Striped Dress",
    year: "1895",
    originalSize: "65.7 x 58.7 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-045",
    basePrice: 3003,
    currency: "AED",
    image: "/image/v/Woman In a Striped Dress.jpg",
    options: [{ id: 'opt1', width: 65.7, height: 58.7, price: 3003, label: 'Original Size' }],
  },

  {
    title: "Child Wearing A Red Scarf",
    year: "1891",
    originalSize: "29.2 x 17.5 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-046",
    basePrice: 887,
    currency: "AED",
    image: "/image/v/Child Wearing a Red Scarf.jpg",
    options: [{ id: 'opt1', width: 29.2, height: 17.5, price: 887, label: 'Original Size' }],
  },

  {
    title: "Le Vase Bleu",
    year: "1930",
    originalSize: "35 x 27 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-047",
    basePrice: 982,
    currency: "AED",
    image: "/image/v/Le Vase Bleu.jpg",
    options: [{ id: 'opt1', width: 35, height: 27, price: 982, label: 'Original Size' }],
  },

  {
    title: "Children In A Room",
    year: "1909",
    originalSize: "84.5 x 77.7 cm",
    artist: "Edoaurd Vuillard",
    artistLife: "1868-1940",
    sku: "AM-V-048",
    basePrice: 2916,
    currency: "AED",
    image: "/image/v/Children In a Room.jpg",
    options: [{ id: 'opt1', width: 84.5, height: 77.7, price: 2916, label: 'Original Size' }],
  },

];

export default vArtworks;
