export const wArtworks = [
  {
    title: "The Lady Of Shallotte",
    year: "1888",
    originalSize: "153 x 200 cm",
    artist: "John William Waterhouse",
    artistLife: "1849-1917",
    sku: "AM-W-001",
    basePrice: 10560,
    currency: "AED",
    image: "/image/w/The Lady of Shallotte.jpg",
    options: [{ id: 'opt1', width: 153, height: 200, price: 10560, label: 'Original Size' }],
  },

  {
    title: "Hylas And Nymphs",
    year: "1896",
    originalSize: "132.1 x 197.5 cm",
    artist: "John William Waterhouse",
    artistLife: "1849-1917",
    sku: "AM-W-002",
    basePrice: 20675,
    currency: "AED",
    image: "/image/w/Hylas And Nymphs.jpg",
    options: [{ id: 'opt1', width: 132.1, height: 197.5, price: 20675, label: 'Original Size' }],
  },

  {
    title: "Orphelia",
    year: "1910",
    originalSize: "101.5 x 63.5 cm",
    artist: "John William Waterhouse",
    artistLife: "1849-1917",
    sku: "AM-W-003",
    basePrice: 5474,
    currency: "AED",
    image: "/image/w/Orphelia.jpg",
    options: [{ id: 'opt1', width: 101.5, height: 63.5, price: 5474, label: 'Original Size' }],
  },

  {
    title: "The Tale Of Decameron",
    year: "1916",
    originalSize: "101 x 159 cm",
    artist: "John William Waterhouse",
    artistLife: "1849-1917",
    sku: "AM-W-004",
    basePrice: 14429,
    currency: "AED",
    image: "/image/w/The Tale of Decameron.jpg",
    options: [{ id: 'opt1', width: 101, height: 159, price: 14429, label: 'Original Size' }],
  },

  {
    title: "I Am Half Sick Of The Shadows Said The Lady Of Shallot",
    year: "1916",
    originalSize: "100.3 x 73.6 cm",
    artist: "John William Waterhouse",
    artistLife: "1849-1917",
    sku: "AM-W-005",
    basePrice: 8106,
    currency: "AED",
    image: "/image/w/I Am Half Sick of the Shadows Said the Lady of Shallot.jpg",
    options: [{ id: 'opt1', width: 100.3, height: 73.6, price: 8106, label: 'Original Size' }],
  },

  {
    title: "Destiny",
    year: "1900",
    originalSize: "68.5 x 54.6 cm",
    artist: "John William Waterhouse",
    artistLife: "1849-1917",
    sku: "AM-W-006",
    basePrice: 4454,
    currency: "AED",
    image: "/image/w/Destiny.jpg",
    options: [{ id: 'opt1', width: 68.5, height: 54.6, price: 4454, label: 'Original Size' }],
  },

  {
    title: "Actors Of The Comedie-Francais",
    year: "1714",
    originalSize: "20 x 25 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-007",
    basePrice: 8818,
    currency: "AED",
    image: "/image/w/Actors Of the Comedie-Francais.jpg",
    options: [{ id: 'opt1', width: 20, height: 25, price: 8818, label: 'Original Size' }],
  },

  {
    title: "Les Champs Elisees",
    year: "1717",
    originalSize: "33.1 x 42.6 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-008",
    basePrice: 11092,
    currency: "AED",
    image: "/image/w/Les Champs Elisees.jpg",
    options: [{ id: 'opt1', width: 33.1, height: 42.6, price: 11092, label: 'Original Size' }],
  },

  {
    title: "The Festival Of Love (The Pleasures Of Love)",
    year: "1717",
    originalSize: "81 x 75 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-009",
    basePrice: 8910,
    currency: "AED",
    image: "/image/w/The Festival of Love (The Pleasures of Love).jpg",
    options: [{ id: 'opt1', width: 81, height: 75, price: 8910, label: 'Original Size' }],
  },

  {
    title: "The Fortune Teller",
    year: "1710",
    originalSize: "37.1 x 27.9 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-010",
    basePrice: 9932,
    currency: "AED",
    image: "/image/w/The Fortune Teller.jpg",
    options: [{ id: 'opt1', width: 37.1, height: 27.9, price: 9932, label: 'Original Size' }],
  },

  {
    title: "Dianna Bathing",
    year: "1715",
    originalSize: "80 x 101 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-011",
    basePrice: 9138,
    currency: "AED",
    image: "/image/w/Dianna Bathing.jpg",
    options: [{ id: 'opt1', width: 80, height: 101, price: 9138, label: 'Original Size' }],
  },

  {
    title: "Pleasures Of The Ball",
    year: "1715",
    originalSize: "52.6 x 65.4 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-012",
    basePrice: 22124,
    currency: "AED",
    image: "/image/w/Pleasures Of the Ball.jpg",
    options: [{ id: 'opt1', width: 52.6, height: 65.4, price: 22124, label: 'Original Size' }],
  },

  {
    title: "A Lady At Her Toilet",
    year: "1716",
    originalSize: "45.2 x 37.8 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-013",
    basePrice: 8444,
    currency: "AED",
    image: "/image/w/A Lady at Her Toilet.jpg",
    options: [{ id: 'opt1', width: 45.2, height: 37.8, price: 8444, label: 'Original Size' }],
  },

  {
    title: "The Shy Lover",
    year: "1718",
    originalSize: "55 x 43 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-014",
    basePrice: 9048,
    currency: "AED",
    image: "/image/w/The Shy Lover.jpg",
    options: [{ id: 'opt1', width: 55, height: 43, price: 9048, label: 'Original Size' }],
  },

  {
    title: "The Spring Fete Champetre In A Water Garden With Figures In A Boat",
    year: "Unknown",
    originalSize: "32.4 x 45.7 cm",
    artist: "Jean Antoine Matteau",
    artistLife: "1684-1721",
    sku: "AM-W-015",
    basePrice: 12048,
    currency: "AED",
    image: "/image/w/The Spring Fete Champetre in A Water Garden with Figures in A Boat.jpg",
    options: [{ id: 'opt1', width: 32.4, height: 45.7, price: 12048, label: 'Original Size' }],
  },

  {
    title: "Along The Ghats Malhuta",
    year: "1880",
    originalSize: "78.8 x 99 cm",
    artist: "Edwin Lord Weeks",
    artistLife: "1849-1903",
    sku: "AM-W-016",
    basePrice: 4439,
    currency: "AED",
    image: "/image/w/Along The Ghats Malhuta.jpg",
    options: [{ id: 'opt1', width: 78.8, height: 99, price: 4439, label: 'Original Size' }],
  },

  {
    title: "The Nautch",
    year: "1900",
    originalSize: "100.5 x 127 cm",
    artist: "Edwin Lord Weeks",
    artistLife: "1849-1903",
    sku: "AM-W-017",
    basePrice: 24157,
    currency: "AED",
    image: "/image/w/The Nautch.jpg",
    options: [{ id: 'opt1', width: 100.5, height: 127, price: 24157, label: 'Original Size' }],
  },

  {
    title: "Departure For The Hunt",
    year: "Unknown",
    originalSize: "87.3 x 122 cm",
    artist: "Edwin Lord Weeks",
    artistLife: "1849-1903",
    sku: "AM-W-018",
    basePrice: 18549,
    currency: "AED",
    image: "/image/w/Departure For the Hunt.jpg",
    options: [{ id: 'opt1', width: 87.3, height: 122, price: 18549, label: 'Original Size' }],
  },

  {
    title: "The Arrival Of Prince Humbert, The Rajah At The Palace Of Amber",
    year: "1888",
    originalSize: "99 x 132 cm",
    artist: "Edwin Lord Weeks",
    artistLife: "1849-1903",
    sku: "AM-W-019",
    basePrice: 19412,
    currency: "AED",
    image: "/image/w/The Arrival of Prince Humbert, The Rajah at the Palace of Amber.jpg",
    options: [{ id: 'opt1', width: 99, height: 132, price: 19412, label: 'Original Size' }],
  },

  {
    title: "Dead Hare And Partridges",
    year: "1702",
    originalSize: "87.3 x 70.5 cm",
    artist: "Jan Weenix",
    artistLife: "1621-1660",
    sku: "AM-W-020",
    basePrice: 9257,
    currency: "AED",
    image: "/image/w/Dead Hare and Partridges.jpg",
    options: [{ id: 'opt1', width: 87.3, height: 70.5, price: 9257, label: 'Original Size' }],
  },

  {
    title: "The White Peacock",
    year: "1692",
    originalSize: "191 x 166 cm",
    artist: "Jan Weenix",
    artistLife: "1621-1660",
    sku: "AM-W-021",
    basePrice: 43140,
    currency: "AED",
    image: "/image/w/The White Peacock.jpg",
    options: [{ id: 'opt1', width: 191, height: 166, price: 43140, label: 'Original Size' }],
  },

  {
    title: "Portrait Of A Hazewindhoud And A Young Partridge Dog",
    year: "1665",
    originalSize: "84 x 103 cm",
    artist: "Jan Weenix",
    artistLife: "1621-1660",
    sku: "AM-W-022",
    basePrice: 6902,
    currency: "AED",
    image: "/image/w/Portrait Of a Hazewindhoud and A Young Partridge Dog.jpg",
    options: [{ id: 'opt1', width: 84, height: 103, price: 6902, label: 'Original Size' }],
  },

  {
    title: "The Ballerina Ulla Poulsen In The Ballet Chopinana",
    year: "1927",
    originalSize: "76 x 91 cm",
    artist: "Gerder Wegener",
    artistLife: "1886-1940",
    sku: "AM-W-023",
    basePrice: 5360,
    currency: "AED",
    image: "/image/w/The Ballerina Ulla Poulsen in the Ballet Chopinana.jpg",
    options: [{ id: 'opt1', width: 76, height: 91, price: 5360, label: 'Original Size' }],
  },

  {
    title: "Lili With A Feathered Fan",
    year: "1920",
    originalSize: "82 x 61 cm",
    artist: "Gerder Wegener",
    artistLife: "1886-1940",
    sku: "AM-W-024",
    basePrice: 4734,
    currency: "AED",
    image: "/image/w/Lili With a Feathered Fan.jpg",
    options: [{ id: 'opt1', width: 82, height: 61, price: 4734, label: 'Original Size' }],
  },

  {
    title: "Two Cocottes With Hats (Lili And Friend)",
    year: "1925",
    originalSize: "56 x 41 cm",
    artist: "Gerder Wegener",
    artistLife: "1886-1940",
    sku: "AM-W-025",
    basePrice: 4587,
    currency: "AED",
    image: "/image/w/Two Cocottes with Hats (Lili and Friend).jpg",
    options: [{ id: 'opt1', width: 56, height: 41, price: 4587, label: 'Original Size' }],
  },

  {
    title: "The Mask",
    year: "1922",
    originalSize: "98 x 81 cm",
    artist: "Gerder Wegener",
    artistLife: "1886-1940",
    sku: "AM-W-026",
    basePrice: 4501,
    currency: "AED",
    image: "/image/w/The Mask.jpg",
    options: [{ id: 'opt1', width: 98, height: 81, price: 4501, label: 'Original Size' }],
  },

  {
    title: "On The Anacapri Road",
    year: "1922",
    originalSize: "96 x 85 cm",
    artist: "Gerder Wegener",
    artistLife: "1886-1940",
    sku: "AM-W-027",
    basePrice: 5502,
    currency: "AED",
    image: "/image/w/On The Anacapri Road.jpg",
    options: [{ id: 'opt1', width: 96, height: 85, price: 5502, label: 'Original Size' }],
  },

  {
    title: "The Conservatory At Carlton House",
    year: "1819",
    originalSize: "50 x 40 cm",
    artist: "Charles Wild",
    artistLife: "1871-1835",
    sku: "AM-W-028",
    basePrice: 6885,
    currency: "AED",
    image: "/image/w/The Conservatory at Carlton House.jpg",
    options: [{ id: 'opt1', width: 50, height: 40, price: 6885, label: 'Original Size' }],
  },

  {
    title: "The Conservatory At Carlton House Pyne's Private Residence",
    year: "Unknown",
    originalSize: "50 x 40 cm",
    artist: "Charles Wild",
    artistLife: "1871-1835",
    sku: "AM-W-029",
    basePrice: 7658,
    currency: "AED",
    image: "/image/w/The Conservatory at Carlton House Pyne's Private Residence.jpg",
    options: [{ id: 'opt1', width: 50, height: 40, price: 7658, label: 'Original Size' }],
  },

  {
    title: "Interior Of St Georges Chapel Windsor",
    year: "1819",
    originalSize: "71 x 56 cm",
    artist: "Charles Wild",
    artistLife: "1871-1835",
    sku: "AM-W-030",
    basePrice: 9410,
    currency: "AED",
    image: "/image/w/Interior Of St Georges Chapel Windsor.jpg",
    options: [{ id: 'opt1', width: 71, height: 56, price: 9410, label: 'Original Size' }],
  },

  {
    title: "An Elegant Beauty",
    year: "Unknown",
    originalSize: "63.5 x 53.5 cm",
    artist: "William Clark Wotner",
    artistLife: "1857-1930",
    sku: "AM-W-031",
    basePrice: 6885,
    currency: "AED",
    image: "/image/w/An Elegant Beauty.jpg",
    options: [{ id: 'opt1', width: 63.5, height: 53.5, price: 6885, label: 'Original Size' }],
  },

  {
    title: "The Jade Necklace",
    year: "1908",
    originalSize: "152.4 x 104 cm",
    artist: "William Clark Wotner",
    artistLife: "1857-1930",
    sku: "AM-W-032",
    basePrice: 10498,
    currency: "AED",
    image: "/image/w/The Jade Necklace.jpg",
    options: [{ id: 'opt1', width: 152.4, height: 104, price: 10498, label: 'Original Size' }],
  },

  {
    title: "The Basket Of Anemones",
    year: "1913",
    originalSize: "130 x 51 cm",
    artist: "William Clark Wotner",
    artistLife: "1857-1930",
    sku: "AM-W-033",
    basePrice: 7558,
    currency: "AED",
    image: "/image/w/The Basket of Anemones.jpg",
    options: [{ id: 'opt1', width: 130, height: 51, price: 7558, label: 'Original Size' }],
  },

  {
    title: "The False God",
    year: "Unknown",
    originalSize: "76.2 x 63.5 cm",
    artist: "William Clark Wotner",
    artistLife: "1857-1930",
    sku: "AM-W-034",
    basePrice: 5944,
    currency: "AED",
    image: "/image/w/The False God.jpg",
    options: [{ id: 'opt1', width: 76.2, height: 63.5, price: 5944, label: 'Original Size' }],
  },

  {
    title: "American Gothic",
    year: "1930",
    originalSize: "78 x 65.3 cm",
    artist: "Grant Wood",
    artistLife: "1891-1942",
    sku: "AM-W-035",
    basePrice: 13000,
    currency: "AED",
    image: "/image/w/American Gothic.jpg",
    options: [{ id: 'opt1', width: 78, height: 65.3, price: 13000, label: 'Original Size' }],
  },

  {
    title: "Stone City Iowa",
    year: "1930",
    originalSize: "76.8 x 101.8 cm",
    artist: "Grant Wood",
    artistLife: "1891-1942",
    sku: "AM-W-036",
    basePrice: 5076,
    currency: "AED",
    image: "/image/w/Stone City Iowa.jpg",
    options: [{ id: 'opt1', width: 76.8, height: 101.8, price: 5076, label: 'Original Size' }],
  },

  {
    title: "A Girl Reading A Letter With An Old Man",
    year: "1767",
    originalSize: "91.5 x 71 cm",
    artist: "Joseph Wright Of Derby",
    artistLife: "1734-1797",
    sku: "AM-W-037",
    basePrice: 8503,
    currency: "AED",
    image: "/image/w/A Girl Reading a Letter with An Old Man.jpg",
    options: [{ id: 'opt1', width: 91.5, height: 71, price: 8503, label: 'Original Size' }],
  },

  {
    title: "A Girl Reading A Letter By Candle Light With A Young Man",
    year: "1760",
    originalSize: "89 x 69.8 cm",
    artist: "Joseph Wright Of Derby",
    artistLife: "1734-1797",
    sku: "AM-W-038",
    basePrice: 7337,
    currency: "AED",
    image: "/image/w/A Girl Reading A Letter By Candle Light With A Young Man.jpg",
    options: [{ id: 'opt1', width: 89, height: 69.8, price: 7337, label: 'Original Size' }],
  },

  {
    title: "Miravan Breaking Open The Tomb Of His Ancestors",
    year: "1772",
    originalSize: "103 x 81 cm",
    artist: "Joseph Wright Of Derby",
    artistLife: "1734-1797",
    sku: "AM-W-039",
    basePrice: 12262,
    currency: "AED",
    image: "/image/w/Miravan Breaking Open the Tomb of His Ancestors.jpg",
    options: [{ id: 'opt1', width: 103, height: 81, price: 12262, label: 'Original Size' }],
  },

  {
    title: "An Eruption Of Vesuvius Seen From Portici",
    year: "1774",
    originalSize: "91 x 112 cm",
    artist: "Joseph Wright Of Derby",
    artistLife: "1734-1797",
    sku: "AM-W-040",
    basePrice: 6261,
    currency: "AED",
    image: "/image/w/An Eruption of Vesuvius Seen from Portici.jpg",
    options: [{ id: 'opt1', width: 91, height: 112, price: 6261, label: 'Original Size' }],
  },

];

export default wArtworks;
