export const zArtworks = [
  {
    title: "The Favourite Of The King",
    year: "1867",
    originalSize: "56 x 45 cm",
    artist: "Eduardo Zamacois Y Zabala",
    artistLife: "1842-1871",
    sku: "AM-Z-001",
    basePrice: 23511,
    currency: "AED",
    image: "/image/z/The Favourite of the King.jpg",
    options: [{ id: 'opt1', width: 56, height: 45, price: 23511, label: 'Original Size' }],
  },

  {
    title: "A Momentary Diversion",
    year: "1868",
    originalSize: "35.5 x 27 cm",
    artist: "Eduardo Zamacois Y Zabala",
    artistLife: "1842-1871",
    sku: "AM-Z-002",
    basePrice: 11590,
    currency: "AED",
    image: "/image/z/A Momentary Diversion.jpg",
    options: [{ id: 'opt1', width: 35.5, height: 27, price: 11590, label: 'Original Size' }],
  },

  {
    title: "In Werners Rowing Boat",
    year: "1917",
    originalSize: "82 x 51 cm",
    artist: "Anders Zorn",
    artistLife: "1860-1920",
    sku: "AM-Z-003",
    basePrice: 4083,
    currency: "AED",
    image: "/image/z/In Werners Rowing Boat.jpg",
    options: [{ id: 'opt1', width: 82, height: 51, price: 4083, label: 'Original Size' }],
  },

  {
    title: "Morning Toilet With His Mother",
    year: "1888",
    originalSize: "60 x 36 cm",
    artist: "Anders Zorn",
    artistLife: "1860-1920",
    sku: "AM-Z-004",
    basePrice: 2961,
    currency: "AED",
    image: "/image/z/Morning Toilet with His Mother.jpg",
    options: [{ id: 'opt1', width: 60, height: 36, price: 2961, label: 'Original Size' }],
  },

  {
    title: "Night Effect",
    year: "1895",
    originalSize: "101 x 66 cm",
    artist: "Anders Zorn",
    artistLife: "1860-1920",
    sku: "AM-Z-005",
    basePrice: 4813,
    currency: "AED",
    image: "/image/z/Night Effect.jpg",
    options: [{ id: 'opt1', width: 101, height: 66, price: 4813, label: 'Original Size' }],
  },

  {
    title: "Opal",
    year: "1891",
    originalSize: "100.3 x 69.5 cm",
    artist: "Anders Zorn",
    artistLife: "1860-1920",
    sku: "AM-Z-006",
    basePrice: 4334,
    currency: "AED",
    image: "/image/z/Opal.jpg",
    options: [{ id: 'opt1', width: 100.3, height: 69.5, price: 4334, label: 'Original Size' }],
  },

  {
    title: "St Francis In Ecstasy",
    year: "1660",
    originalSize: "66 x 53 cm",
    artist: "Francisco de Zurbaran",
    artistLife: "1598-1664",
    sku: "AM-Z-007",
    basePrice: 4368,
    currency: "AED",
    image: "/image/z/St Francis In Ecstasy.jpg",
    options: [{ id: 'opt1', width: 66, height: 53, price: 4368, label: 'Original Size' }],
  },

  {
    title: "Agnus Dei",
    year: "1635",
    originalSize: "37.3 x 62 cm",
    artist: "Francisco de Zurbaran",
    artistLife: "1598-1664",
    sku: "AM-Z-008",
    basePrice: 4666,
    currency: "AED",
    image: "/image/z/Agnus Dei.jpg",
    options: [{ id: 'opt1', width: 37.3, height: 62, price: 4666, label: 'Original Size' }],
  },

  {
    title: "St Francis In Meditation",
    year: "1639",
    originalSize: "162 x 137 cm",
    artist: "Francisco de Zurbaran",
    artistLife: "1598-1664",
    sku: "AM-Z-009",
    basePrice: 10360,
    currency: "AED",
    image: "/image/z/St Francis In Meditation.jpg",
    options: [{ id: 'opt1', width: 162, height: 137, price: 10360, label: 'Original Size' }],
  },

  {
    title: "The Immaculate Conception",
    year: "Unknown",
    originalSize: "91 x 71 cm",
    artist: "Francisco de Zurbaran",
    artistLife: "1598-1664",
    sku: "AM-Z-010",
    basePrice: 7360,
    currency: "AED",
    image: "/image/z/The Immaculate Conception.jpg",
    options: [{ id: 'opt1', width: 91, height: 71, price: 7360, label: 'Original Size' }],
  },

  {
    title: "A Cup Of Water And A Rose On A Silver Plate",
    year: "1630",
    originalSize: "21.2 x 30.1 cm",
    artist: "Francisco de Zurbaran",
    artistLife: "1598-1664",
    sku: "AM-Z-011",
    basePrice: 3932,
    currency: "AED",
    image: "/image/z/A Cup of Water and A Rose on A Silver Plate.jpg",
    options: [{ id: 'opt1', width: 21.2, height: 30.1, price: 3932, label: 'Original Size' }],
  },

];

export default zArtworks;
